import { discoverEnvKeys } from "@/lib/services/env-discovery-service";
import { generateEnvSecret } from "@/lib/services/env-secret-service";
import { validateEnvKeyValue } from "@/lib/services/env-validation-service";

export const PANDORA_VERCEL_PROJECT = { provider: "vercel", providerProjectId: "prj_yUjuF1XBbTR6f89vkEhn1xtN5I4F", providerProjectName: "memory", providerTeamId: "team_szQXqABERd5jcUrAZGmIa8Hg", productionUrl: "pandorasmemory.vercel.app", displayName: "Pandora Memory" } as const;
export const PANDORA_AUTOPILOT_VALUES = ["off", "suggest", "queue", "capture_low_risk"] as const;
export const PHASE5C_SAFE_PRODUCTION = { PANDORA_ENABLE_MEMORY_DISTILLATION: "true", PANDORA_ENABLE_MODEL_CALLS: "false", PANDORA_ENABLE_EMBEDDINGS: "false", PANDORA_ENABLE_SEMANTIC_RETRIEVAL: "false", PANDORA_ENABLE_PUBLIC_MEMORY_READ: "false", PANDORA_ENABLE_PUBLIC_MEMORY_PERSISTENCE: "false", PANDORA_ENABLE_AUTO_CAPTURE: "false", PANDORA_SENSITIVE_MEMORY_REQUIRES_APPROVAL: "true" } as const;
export const PHASE5A_QUEUE_SAFE = { PANDORA_ENABLE_MEMORY_AUTOPILOT: "true", PANDORA_MEMORY_AUTOPILOT: "queue", PANDORA_AUTO_RETRIEVE: "true", PANDORA_AUTO_CANDIDATE_QUEUE: "true", PANDORA_AUTO_CAPTURE_LOW_RISK: "false", PANDORA_SENSITIVE_MEMORY_REQUIRES_APPROVAL: "true", PANDORA_ENABLE_MEMORY_CONTEXT_API: "true", PANDORA_ENABLE_MEMORY_CAPTURE_API: "true" } as const;

export function isBrokerEnabled(env: Partial<NodeJS.ProcessEnv> = process.env) { return env.PANDORA_ENV_BROKER_ENABLED === "true"; }
export function buildEnvCatalog() { return discoverEnvKeys().map((item) => ({ ...item, managed: item.classificationSuggestion !== "unknown", allowedValues: item.key === "PANDORA_MEMORY_AUTOPILOT" ? [...PANDORA_AUTOPILOT_VALUES] : item.classificationSuggestion === "runtime_flag" ? ["true", "false"] : undefined, safeDefault: item.defaultSuggestion })); }
export function generateManagedSecret(key: string) { if (key !== "PANDORA_INTERNAL_JOB_TOKEN") throw new Error("unsupported_generated_secret"); return generateEnvSecret(); }
export function validatePresetValues(values: Record<string, string>) { return Object.entries(values).map(([key, value]) => ({ key, ...validateEnvKeyValue(key, key === "PANDORA_MEMORY_AUTOPILOT" ? "mode" : key.startsWith("PANDORA_") ? "runtime_flag" : "unknown", value, [...PANDORA_AUTOPILOT_VALUES]) })); }
export function getEnvBrokerStatus() { const catalog = buildEnvCatalog(); return { ok: true, brokerEnabled: isBrokerEnabled(), project: PANDORA_VERCEL_PROJECT, totals: { discovered: catalog.length, managed: catalog.filter((i) => i.managed).length, requiredMissing: catalog.filter((i) => i.requiredSuggestion && !process.env[i.key]).length, unknown: catalog.filter((i) => i.classificationSuggestion === "unknown").length, unsafe: catalog.filter((i) => i.key.startsWith("NEXT_PUBLIC_") && i.classificationSuggestion !== "public_safe").length }, catalog: catalog.map((i) => ({ ...i, present: Boolean(process.env[i.key]), fingerprint: process.env[i.key] ? "present_redacted" : null })) }; }
