import type { FirstLiveAppendPhaseCloseReport, FirstLiveAppendProofCaptureExport, FirstLiveAppendProofCaptureInput, FirstLiveAppendProofCapturePackage, FirstLiveAppendProofCaptureResult, FirstLiveAppendProofCaptureSafetySummary } from "@/lib/services/first-live-append-proof-capture-contract";
import { validateFirstLiveAppendProofCapture } from "@/lib/services/first-live-append-proof-capture-validator";
const safety = (ready: boolean): FirstLiveAppendProofCaptureSafetySummary => ({ internalOnly: true, proofCaptureOnly: true, oneItemOnly: true, performsPersistence: false, publicPersistenceEnabled: false, productionIngestEnabled: false, publicReadEnabled: false, wouldCallModel: false, wouldEmbed: false, semanticRetrievalEnabled: false, appendOnlyProofCapture: true, emergencyStopSupported: true, rawUserIdExposed: false, rawIdempotencyKeyExposed: false, memoryTextExposed: false, evidenceExposed: false, serviceRoleExposed: false, rawErrorsExposed: false, phaseReadyToClose: ready });
export async function runFirstLiveAppendProofCapture(input: FirstLiveAppendProofCaptureInput): Promise<FirstLiveAppendProofCaptureResult> {
  const validation = validateFirstLiveAppendProofCapture(input); const p = input.packet; const r = input.workflowReceipt; const pr = input.proofReport;
  if (!validation.ok || !p || !r || !pr) return validation;
  const pkg: FirstLiveAppendProofCapturePackage = { packetId: p.packetId, packetFingerprint: input.packetFingerprint ?? p.packetId, operatorFingerprint: p.operatorFingerprint, namespace: p.namespace, reviewItemId: p.reviewItemId, decisionId: p.decisionId, memoryItemId: r.memoryItemId, sourceId: r.sourceId, previewFingerprint: p.previewFingerprint, idempotencyFingerprint: p.idempotencyFingerprint, workflowReceiptFingerprint: r.receiptFingerprint, proofReportFingerprint: pr.proofReportFingerprint, readbackVerificationStatus: pr.readbackVerification, browserVisibilityStatus: pr.browserVerification, auditVerificationStatus: pr.auditVerification, appendOnlyVerificationStatus: pr.appendOnlyVerification, emergencyStopStatus: "off", finalOperatorNoteFingerprint: pr.finalOperatorNoteFingerprint, phaseCloseStatus: "ready_to_close" };
  const summary = safety(true); const exp: FirstLiveAppendProofCaptureExport = { ...pkg, safetySummary: summary, redacted: true };
  const report: FirstLiveAppendPhaseCloseReport = { title: "First live append phase-close report", status: "ready_to_close", summary: "First controlled live append proof captured. Stop after one item; do not proceed to retrieval.", package: pkg, safetySummary: summary, redacted: true, steps: ["validate packet","validate workflow receipt","validate proof report","verify readback","verify browser visibility","verify audit","verify append-only"].map((label, i) => ({ id: `step_${i + 1}`, label, status: "passed", required: true })), artifacts: ["packet","workflow_receipt","proof_report","readback","browser_visibility","audit","append_only"].map((id) => ({ id, label: id.replaceAll("_", " "), required: true, available: true, redacted: true })) };
  if (input.appendProofRecord) await input.proofRepository?.append(exp);
  return { ok: true, blocked: false, package: pkg, report, export: exp, blockers: [], warnings: [], performedPersistence: false, calledPublicRoute: false, calledModel: false, calledEmbeddings: false, calledSemanticRetrieval: false };
}
