import type { PandoraServerSessionResult } from "@/lib/auth/pandora-server-session-contract";
import type { FirstControlledLiveAppendPacket } from "@/lib/services/first-controlled-live-append-packet-contract";

export type FirstLiveAppendProofCaptureStep = { id: string; label: string; status: "passed" | "blocked" | "pending"; required: true };
export type FirstLiveAppendProofCaptureBlocker = { code: string; message: string; redacted: true };
export type FirstLiveAppendProofCaptureWarning = { code: string; message: string; redacted: true };
export type FirstLiveAppendProofCaptureArtifact = { id: string; label: string; required: true; available: boolean; redacted: true };
export type VerificationStatus = "passed" | "failed" | "missing";
export type FirstLiveAppendWorkflowReceipt = { receiptId: string; receiptFingerprint: string; executionHappened: boolean; namespace: string; reviewItemId: string; decisionId: string; memoryItemId: string; sourceId: string; previewFingerprint: string; idempotencyFingerprint: string };
export type FirstLiveAppendProofReport = { proofReportId: string; proofReportFingerprint: string; receiptFingerprint: string; namespace: string; memoryItemId: string; readbackVerification: VerificationStatus; browserVerification: VerificationStatus; auditVerification: VerificationStatus; appendOnlyVerification: VerificationStatus; operatorFingerprint: string; finalOperatorNoteFingerprint: string };
export type FirstLiveAppendProofCaptureSafetySummary = { internalOnly: true; proofCaptureOnly: true; oneItemOnly: true; performsPersistence: false; publicPersistenceEnabled: false; productionIngestEnabled: false; publicReadEnabled: false; wouldCallModel: false; wouldEmbed: false; semanticRetrievalEnabled: false; appendOnlyProofCapture: true; emergencyStopSupported: true; rawUserIdExposed: false; rawIdempotencyKeyExposed: false; memoryTextExposed: false; evidenceExposed: false; serviceRoleExposed: false; rawErrorsExposed: false; phaseReadyToClose: boolean };
export type FirstLiveAppendProofCapturePackage = { packetId: string; packetFingerprint: string; operatorFingerprint: string; namespace: string; reviewItemId: string; decisionId: string; memoryItemId: string; sourceId: string; previewFingerprint: string; idempotencyFingerprint: string; workflowReceiptFingerprint: string; proofReportFingerprint: string; readbackVerificationStatus: VerificationStatus; browserVisibilityStatus: VerificationStatus; auditVerificationStatus: VerificationStatus; appendOnlyVerificationStatus: VerificationStatus; emergencyStopStatus: "on" | "off"; finalOperatorNoteFingerprint: string; phaseCloseStatus: "ready_to_close" | "blocked" };
export type FirstLiveAppendPhaseCloseReport = { title: "First live append phase-close report"; status: "ready_to_close" | "blocked"; summary: string; package: FirstLiveAppendProofCapturePackage; safetySummary: FirstLiveAppendProofCaptureSafetySummary; steps: FirstLiveAppendProofCaptureStep[]; artifacts: FirstLiveAppendProofCaptureArtifact[]; redacted: true };
export type FirstLiveAppendProofCaptureExport = Pick<FirstLiveAppendProofCapturePackage, "packetId" | "packetFingerprint" | "operatorFingerprint" | "namespace" | "reviewItemId" | "decisionId" | "memoryItemId" | "sourceId" | "previewFingerprint" | "idempotencyFingerprint" | "workflowReceiptFingerprint" | "proofReportFingerprint" | "readbackVerificationStatus" | "browserVisibilityStatus" | "auditVerificationStatus" | "appendOnlyVerificationStatus" | "emergencyStopStatus" | "finalOperatorNoteFingerprint" | "phaseCloseStatus"> & { safetySummary: FirstLiveAppendProofCaptureSafetySummary; redacted: true };
export type FirstLiveAppendProofCaptureInput = { sessionResult?: PandoraServerSessionResult; namespace?: string; allowedNamespaces?: string[]; packet?: FirstControlledLiveAppendPacket | null; packetFingerprint?: string; packetOneItemOnly?: boolean; packetPerformedPersistence?: boolean; workflowReceipt?: FirstLiveAppendWorkflowReceipt | null; proofReport?: FirstLiveAppendProofReport | null; emergencyStopOn?: boolean; publicPersistenceEnabled?: boolean; productionIngestEnabled?: boolean; publicReadEnabled?: boolean; modelCallsEnabled?: boolean; embeddingsEnabled?: boolean; semanticRetrievalEnabled?: boolean; gptActionsEnabled?: boolean; mcpEnabled?: boolean; serviceRoleExposureDetected?: boolean; capturePackage?: unknown; rawErrors?: unknown; user_id?: unknown; userId?: unknown; proofRepository?: { append: (record: FirstLiveAppendProofCaptureExport) => Promise<void> | void }; appendProofRecord?: boolean };
export type FirstLiveAppendProofCaptureResult = { ok: boolean; blocked: boolean; package?: FirstLiveAppendProofCapturePackage; report?: FirstLiveAppendPhaseCloseReport; export?: FirstLiveAppendProofCaptureExport; blockers: FirstLiveAppendProofCaptureBlocker[]; warnings: FirstLiveAppendProofCaptureWarning[]; performedPersistence: false; calledPublicRoute: false; calledModel: false; calledEmbeddings: false; calledSemanticRetrieval: false };
