/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from "crypto";
import type { MemoryBridgeDbClient, MemoryBridgeNamespace, MemoryEvent } from "@/lib/services/memory-bridge-service";
import { classifyMemoryCandidatesWithProvider } from "@/lib/services/memory-model-provider";
import { detectSecrets, redactSecrets } from "@/lib/services/memory-redaction-service";

export type MemoryCandidateStatus = "pending" | "approved" | "rejected" | "captured" | "blocked_secret" | "duplicate";
export type MemorySensitivity = "low" | "medium" | "high" | "private";
export type MemoryCaptureCandidate = {
  id: string; user_id: string; namespace: MemoryBridgeNamespace; source: string; source_ref?: string | null; raw_excerpt?: string | null; redacted_excerpt?: string | null; memory_type?: string | null; title?: string | null; summary?: string | null; importance?: number | null; sensitivity?: MemorySensitivity | string | null; confidence?: number | null; should_capture?: boolean | null; requires_review?: boolean | null; status: MemoryCandidateStatus; reason?: string | null; people?: unknown[] | null; projects?: unknown[] | null; risks?: unknown[] | null; tags?: unknown[] | null; metadata?: Record<string, any> | null; created_at?: string | null; reviewed_at?: string | null; captured_event_id?: string | null;
};
export type CandidateReviewResult<T> = { ok: true; data: T; blockers: string[]; warnings: string[]; next_step?: string } | { ok: false; data?: T; blockers: string[]; warnings: string[]; next_step: string };

export function hashContent(text:string){return createHash("sha256").update(text.trim().toLowerCase()).digest("hex");}
const secret = "[REDACTED_SECRET]";
const now = () => new Date().toISOString();
const arr = (v: unknown) => Array.isArray(v) ? v : [];
function mergeReview(candidate: MemoryCaptureCandidate, patch: Record<string, unknown>) { return { ...(candidate.metadata ?? {}), review: { ...((candidate.metadata ?? {}).review ?? {}), ...patch, updated_at: now() } }; }
async function feedback(client: MemoryBridgeDbClient, input: { userId: string; namespace: MemoryBridgeNamespace; candidate?: MemoryCaptureCandidate; action: string; newStatus?: string; review_note?: string; reason?: string; metadata?: Record<string, unknown> }) { try { await client.from("memory_feedback_events").insert({ user_id: input.userId, namespace: input.namespace, candidate_id: input.candidate?.id, action: input.action, old_status: input.candidate?.status, new_status: input.newStatus, old_memory_type: input.candidate?.memory_type, new_memory_type: input.metadata?.new_memory_type, old_sensitivity: input.candidate?.sensitivity, new_sensitivity: input.metadata?.new_sensitivity, review_note: input.review_note, reason: input.reason, metadata: input.metadata ?? {} }).select("*").single(); return null; } catch (e) { return e instanceof Error ? e.message : "feedback_write_failed"; } }
export async function getCandidateForReview(client: MemoryBridgeDbClient, input: { id: string; userId: string; namespace: MemoryBridgeNamespace }): Promise<CandidateReviewResult<MemoryCaptureCandidate>> { const r = await client.from<MemoryCaptureCandidate>("memory_capture_candidates").select("*").eq("id", input.id).eq("user_id", input.userId).eq("namespace", input.namespace).single(); if (r.error || !r.data) return { ok: false, blockers: ["candidate_not_found"], warnings: r.error?.message ? [r.error.message] : [], next_step: "Check candidate id, user, and namespace." }; const c = r.data.status === "blocked_secret" ? { ...r.data, raw_excerpt: secret, redacted_excerpt: secret, summary: r.data.summary === secret ? secret : r.data.summary } : r.data; return { ok: true, data: c, blockers: [], warnings: [] }; }
async function updateCandidate(client: MemoryBridgeDbClient, candidate: MemoryCaptureCandidate, patch: Record<string, unknown>, blocker = "candidate_update_failed"): Promise<CandidateReviewResult<MemoryCaptureCandidate>> { const r = await client.from<MemoryCaptureCandidate>("memory_capture_candidates").update(patch).eq("id", candidate.id).eq("user_id", candidate.user_id).eq("namespace", candidate.namespace).select("*").single(); if (r.error || !r.data) return { ok: false, blockers: [blocker], warnings: [r.error?.message ?? "unknown update failure"], next_step: "Check candidate schema and RLS." }; return { ok: true, data: r.data, blockers: [], warnings: [] }; }
export async function approveCandidateForReview(client: MemoryBridgeDbClient, input: { id: string; userId: string; namespace: MemoryBridgeNamespace; review_note?: string }) { const got = await getCandidateForReview(client, input); if (!got.ok) return got; if (got.data.status === "blocked_secret") return { ok: false as const, blockers: ["blocked_secret_cannot_be_approved"], warnings: [], next_step: "Reject or mark duplicate; do not approve secrets." }; const metadata = mergeReview(got.data, { approved: true, review_note: input.review_note }); const r = await updateCandidate(client, got.data, { status: "approved", reviewed_at: now(), metadata }); await feedback(client, { userId: input.userId, namespace: input.namespace, candidate: got.data, action: "approve", newStatus: "approved", review_note: input.review_note }); return r; }
export async function rejectCandidateForReview(client: MemoryBridgeDbClient, input: { id: string; userId: string; namespace: MemoryBridgeNamespace; review_note?: string; reason?: string }) { const got = await getCandidateForReview(client, input); if (!got.ok) return got; const metadata = mergeReview(got.data, { rejected: true, review_note: input.review_note, reason: input.reason }); const r = await updateCandidate(client, got.data, { status: "rejected", reviewed_at: now(), reason: input.reason ?? got.data.reason, metadata }); await feedback(client, { userId: input.userId, namespace: input.namespace, candidate: got.data, action: "reject", newStatus: "rejected", review_note: input.review_note, reason: input.reason }); return r; }
export async function editCandidateForReview(client: MemoryBridgeDbClient, input: { id: string; userId: string; namespace: MemoryBridgeNamespace; title: string; summary: string; memory_type: string; sensitivity: MemorySensitivity; importance: number; tags?: unknown[]; risks?: unknown[]; people?: unknown[]; projects?: unknown[] }) { const got = await getCandidateForReview(client, input); if (!got.ok) return got; if (got.data.status === "blocked_secret") return { ok: false as const, blockers: ["secret_detected_in_edit"], warnings: [], next_step: "Blocked secret candidates cannot be edited into unblocked content." }; const text = [input.title, input.summary, input.memory_type, ...arr(input.tags), ...arr(input.risks), ...arr(input.people), ...arr(input.projects)].join("\n"); if (detectSecrets(text).detected) { await updateCandidate(client, got.data, { status: "blocked_secret", raw_excerpt: secret, redacted_excerpt: secret, summary: secret, sensitivity: "private", requires_review: true, should_capture: false, reviewed_at: now(), metadata: mergeReview(got.data, { edit_blocked: true }) }); return { ok: false as const, blockers: ["secret_detected_in_edit"], warnings: [], next_step: "Remove credentials/secrets before editing candidates." }; } const patch = { title: redactSecrets(input.title), summary: redactSecrets(input.summary), redacted_excerpt: redactSecrets(input.summary), memory_type: input.memory_type, sensitivity: input.sensitivity, importance: Math.min(Math.max(Number(input.importance), 1), 10), tags: arr(input.tags), risks: arr(input.risks), people: arr(input.people), projects: arr(input.projects), metadata: mergeReview(got.data, { edited: true, previous_title: got.data.title, previous_summary: got.data.summary }) }; const r = await updateCandidate(client, got.data, patch); await feedback(client, { userId: input.userId, namespace: input.namespace, candidate: got.data, action: "edit", newStatus: got.data.status, metadata: { new_memory_type: input.memory_type, new_sensitivity: input.sensitivity } }); return r; }
export async function markCandidateDuplicate(client: MemoryBridgeDbClient, input: { id: string; userId: string; namespace: MemoryBridgeNamespace; duplicate_of_candidate_id?: string; review_note?: string }) { const got = await getCandidateForReview(client, input); if (!got.ok) return got; const metadata = mergeReview(got.data, { duplicate_of_candidate_id: input.duplicate_of_candidate_id, review_note: input.review_note }); const r = await updateCandidate(client, got.data, { status: "duplicate", reviewed_at: now(), metadata }); await feedback(client, { userId: input.userId, namespace: input.namespace, candidate: got.data, action: "duplicate", newStatus: "duplicate", review_note: input.review_note }); return r; }
export async function captureApprovedCandidate(client: MemoryBridgeDbClient, candidateOrInput:any, maybeUserId?:string) { const input = typeof candidateOrInput?.id === "string" && candidateOrInput?.userId ? candidateOrInput : { candidate: candidateOrInput, userId: maybeUserId, namespace: candidateOrInput?.namespace }; const candidate: MemoryCaptureCandidate | undefined = input.candidate ?? (await getCandidateForReview(client, { id: input.id, userId: input.userId, namespace: input.namespace })).data; if (!candidate) return { ok: false as const, blockers: ["candidate_not_found"], warnings: [], next_step: "Check candidate id." }; if (candidate.status === "captured") return { ok: false as const, blockers: ["candidate_already_captured"], warnings: [], next_step: "Use the existing captured_event_id." }; if (candidate.status === "blocked_secret") return { ok: false as const, blockers: ["blocked_secret_cannot_be_captured"], warnings: [], next_step: "Reject or mark duplicate; do not capture secrets." }; if (candidate.status === "rejected") return { ok: false as const, blockers: ["candidate_rejected"], warnings: [], next_step: "Only approved candidates can be captured." }; if (candidate.status === "duplicate") return { ok: false as const, blockers: ["candidate_duplicate"], warnings: [], next_step: "Do not capture duplicate candidates." }; if (candidate.status !== "approved") return { ok: false as const, blockers: ["candidate_not_approved"], warnings: [], next_step: "Approve the candidate before capture." }; const raw = redactSecrets(candidate.redacted_excerpt || candidate.summary || candidate.title || ""); const row={user_id:input.userId,namespace:candidate.namespace,source:candidate.source,source_ref:candidate.source_ref,raw_text:raw,extracted_summary:redactSecrets(candidate.summary || raw),importance:candidate.importance,sensitivity:candidate.sensitivity,status:"captured",created_by:input.userId}; const ev=await client.from<MemoryEvent>("memory_events").insert(row).select("*").single(); if(ev.error||!ev.data) return { ok:false as const, blockers:["candidate_capture_failed"], warnings:[ev.error?.message??"unknown capture failure"], next_step:"Check memory_events schema and RLS."}; const upd=await updateCandidate(client,candidate,{status:"captured",captured_event_id:ev.data.id,reviewed_at:now(),metadata:mergeReview(candidate,{captured_event_id:ev.data.id})},"candidate_update_failed"); await feedback(client,{userId:input.userId,namespace:candidate.namespace,candidate,action:"capture",newStatus:"captured",metadata:{captured_event_id:ev.data.id}}); return upd.ok ? { ok:true as const, data:{candidate:upd.data,event:ev.data}, blockers:[], warnings:[] } : upd; }
export async function createCandidatesFromSession(client:MemoryBridgeDbClient,input:{user_id:string;namespace:MemoryBridgeNamespace;source:string;source_ref?:string;text:string;mode?:"candidate_only"|"auto_capture_allowed"},env:Partial<NodeJS.ProcessEnv>=process.env){ const inputHasCredential=detectSecrets(input.text).detected; const classified=await classifyMemoryCandidatesWithProvider({namespace:input.namespace,text:input.text,source:input.source,source_ref:input.source_ref},env); const rows=classified.candidates.map(c=>{ const blocked=inputHasCredential||c.memory_type==="secret_or_credential"; return {user_id:input.user_id,namespace:c.namespace,source:input.source,source_ref:input.source_ref,raw_excerpt:blocked?secret:c.raw_excerpt,redacted_excerpt:blocked?secret:redactSecrets(c.raw_excerpt),memory_type:blocked?"secret_or_credential":c.memory_type,title:c.title,summary:blocked?secret:c.summary,importance:blocked?10:c.importance,sensitivity:blocked?"private":c.sensitivity,confidence:c.confidence,should_capture:blocked?false:c.should_capture,requires_review:blocked?true:c.requires_review,status:blocked?"blocked_secret":"pending",reason:blocked?"Secret-like value detected and blocked.":c.reason,people:c.people,projects:c.projects,risks:blocked?["secret_exposure"]:c.risks,tags:blocked?["secret_or_credential"]:c.tags,metadata:{content_hash:hashContent(blocked?"blocked_secret":c.summary)}}}); if(!rows.length)return {candidates:[],warnings:[]}; const result=await client.from("memory_capture_candidates").insert(rows).select("*"); const data=(await (result as unknown as Promise<{data:unknown[]|null;error:{message:string}|null}>)); return {candidates:data.data??rows,warnings:data.error?[data.error.message]:[], model:{...classified.metadata,input_blocked_for_credential:inputHasCredential}}; }
export async function approveCandidate(client:MemoryBridgeDbClient,id:string,userId:string,namespace:MemoryBridgeNamespace){return approveCandidateForReview(client,{id,userId,namespace});}
export async function rejectCandidate(client:MemoryBridgeDbClient,id:string,userId:string,namespace:MemoryBridgeNamespace){return rejectCandidateForReview(client,{id,userId,namespace});}
export async function autoCaptureHighConfidenceCandidate(client:MemoryBridgeDbClient,candidate:any,userId:string,env:Partial<NodeJS.ProcessEnv>=process.env){ if(env.PANDORA_ENABLE_AUTO_CAPTURE!=="true") return {ok:false,reason:"auto_capture_disabled"}; if(candidate.requires_review||["high","private"].includes(candidate.sensitivity)||candidate.memory_type==="secret_or_credential") return {ok:false,reason:"review_required_or_secret"}; if(Number(candidate.confidence)<Number(env.PANDORA_AUTO_CAPTURE_CONFIDENCE_THRESHOLD??0.86)) return {ok:false,reason:"confidence_below_threshold"}; return captureApprovedCandidate(client,{candidate:{...candidate,status:"approved"},userId,namespace:candidate.namespace}); }
export async function detectDuplicateCandidate(){ return {duplicate:false,reason:"deterministic_hash_only"}; }
