/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from "crypto";
import type { MemoryBridgeDbClient, MemoryBridgeNamespace, MemoryEvent } from "@/lib/services/memory-bridge-service";
import { classifyMemoryCandidatesWithProvider } from "@/lib/services/memory-model-provider";
import { redactSecrets } from "@/lib/services/memory-redaction-service";
export function hashContent(text:string){return createHash("sha256").update(text.trim().toLowerCase()).digest("hex");}
export async function createCandidatesFromSession(client:MemoryBridgeDbClient,input:{user_id:string;namespace:MemoryBridgeNamespace;source:string;source_ref?:string;text:string;mode?:"candidate_only"|"auto_capture_allowed"},env:Partial<NodeJS.ProcessEnv>=process.env){ const classified=await classifyMemoryCandidatesWithProvider({namespace:input.namespace,text:input.text,source:input.source,source_ref:input.source_ref},env); const rows=classified.candidates.map(c=>({user_id:input.user_id,namespace:c.namespace,source:input.source,source_ref:input.source_ref,raw_excerpt:c.raw_excerpt,redacted_excerpt:redactSecrets(c.raw_excerpt),memory_type:c.memory_type,title:c.title,summary:c.summary,importance:c.importance,sensitivity:c.sensitivity,confidence:c.confidence,should_capture:c.should_capture,requires_review:c.requires_review,status:c.memory_type==="secret_or_credential"?"blocked_secret":"pending",reason:c.reason,people:c.people,projects:c.projects,risks:c.risks,tags:c.tags,metadata:{content_hash:hashContent(c.summary)}})); if(!rows.length)return {candidates:[],warnings:[]}; const result=await client.from("memory_capture_candidates").insert(rows).select("*"); const data=(await (result as unknown as Promise<{data:unknown[]|null;error:{message:string}|null}>)); return {candidates:data.data??rows,warnings:data.error?[data.error.message]:[], model:classified.metadata}; }
export async function approveCandidate(client:MemoryBridgeDbClient,id:string,userId:string,namespace:MemoryBridgeNamespace){return client.from("memory_capture_candidates").update({status:"approved",reviewed_at:new Date().toISOString()}).eq("id",id).eq("user_id",userId).eq("namespace",namespace).select("*").single();}
export async function rejectCandidate(client:MemoryBridgeDbClient,id:string,userId:string,namespace:MemoryBridgeNamespace){return client.from("memory_capture_candidates").update({status:"rejected",reviewed_at:new Date().toISOString()}).eq("id",id).eq("user_id",userId).eq("namespace",namespace).select("*").single();}
export async function captureApprovedCandidate(client:MemoryBridgeDbClient,candidate:any,userId:string){ const row={user_id:userId,namespace:candidate.namespace,source:candidate.source,source_ref:candidate.source_ref,raw_text:candidate.redacted_excerpt??candidate.summary,extracted_summary:candidate.summary,importance:candidate.importance,sensitivity:candidate.sensitivity,status:"captured",created_by:userId}; const ev=await client.from<MemoryEvent>("memory_events").insert(row).select("*").single(); if(!ev.error&&ev.data) await client.from("memory_capture_candidates").update({status:"captured",captured_event_id:ev.data.id}).eq("id",candidate.id); return ev; }
export async function autoCaptureHighConfidenceCandidate(client:MemoryBridgeDbClient,candidate:any,userId:string,env:Partial<NodeJS.ProcessEnv>=process.env){ if(env.PANDORA_ENABLE_AUTO_CAPTURE!=="true") return {ok:false,reason:"auto_capture_disabled"}; if(candidate.requires_review||["high","private"].includes(candidate.sensitivity)||candidate.memory_type==="secret_or_credential") return {ok:false,reason:"review_required_or_secret"}; if(Number(candidate.confidence)<Number(env.PANDORA_AUTO_CAPTURE_CONFIDENCE_THRESHOLD??0.86)) return {ok:false,reason:"confidence_below_threshold"}; const ev=await captureApprovedCandidate(client,candidate,userId); return {ok:!ev.error,event:ev.data,error:ev.error?.message}; }
export async function detectDuplicateCandidate(){ return {duplicate:false,reason:"deterministic_hash_only"}; }
