/* eslint-disable @typescript-eslint/no-explicit-any */
import { randomUUID } from "node:crypto";
import type { PandoraNamespace } from "@/components/pandora/types";
import { getShadowContextPack } from "@/lib/services/pandora-shadow-context-pack-service";
import { getShadowPackPreflight, type ShadowPackRiskSummary } from "@/lib/services/pandora-shadow-pack-preflight-service";

export type PromotionRequestDbClient = { from: (table: string) => any };
export type PromotionRequestStatus = "draft" | "submitted" | "approved" | "blocked" | "archived";
export type PromotionReviewerDecision = "approved" | "blocked" | "needs_changes";
export type PromotionRequestRow = { id:string; user_id:string; request_id:string; namespace:PandoraNamespace; shadow_pack_id:string; preflight_id:string; active_master_pack_id:string|null; status:PromotionRequestStatus; title:string; summary:string; promotion_plan:Record<string,unknown>; rollback_plan:Record<string,unknown>; risk_snapshot:ShadowPackRiskSummary|Record<string,unknown>; diff_snapshot:Record<string,unknown>; reviewer_notes:string; reviewer_decision:PromotionReviewerDecision|null; warnings:string[]; created_at:string; updated_at:string; submitted_at?:string|null; approved_at?:string|null; blocked_at?:string|null; archived_at?:string|null };
export type PromotionRequestEventRow = { id:string; user_id:string; promotion_request_id:string; shadow_pack_id:string; preflight_id:string; event_type:string; message:string; metadata:Record<string,unknown>; created_at:string };
const NAMESPACES = new Set(["real_life", "au"]); const STATUSES = new Set(["draft","submitted","approved","blocked","archived"]); const DECISIONS = new Set(["approved","blocked","needs_changes"]);
function assertNamespace(v:string): asserts v is PandoraNamespace { if(!NAMESPACES.has(v)) throw new Error(`Unsupported Pandora namespace: ${v}`); }
function assertStatus(v:string): asserts v is PromotionRequestStatus { if(!STATUSES.has(v)) throw new Error(`Unsupported promotion request status: ${v}`); }
function assertDecision(v:string): asserts v is PromotionReviewerDecision { if(!DECISIONS.has(v)) throw new Error(`Unsupported reviewer_decision: ${v}`); }
async function single(q:any){ const r=await q; if(r.error) return null; return Array.isArray(r.data)?r.data[0]??null:r.data??null; }
async function activeMaster(client:PromotionRequestDbClient,userId:string,namespace:PandoraNamespace){ return single(client.from("memory_context_packs").select("id,namespace,pack_type,status").eq("user_id",userId).eq("namespace",namespace).eq("pack_type","master").eq("status","active").limit(1)); }
export async function listPromotionRequests(client:PromotionRequestDbClient,input:{userId:string; namespace?:string; status?:string; limit?:number}):Promise<PromotionRequestRow[]>{ if(input.namespace) assertNamespace(input.namespace); if(input.status) assertStatus(input.status); let q=client.from("pandora_promotion_requests").select("*").eq("user_id",input.userId).order("created_at",{ascending:false}).limit(input.limit??20); if(input.namespace) q=q.eq("namespace",input.namespace); if(input.status) q=q.eq("status",input.status); const r=await q; return r.error?[]:(Array.isArray(r.data)?r.data:[]); }
export async function getPromotionRequest(client:PromotionRequestDbClient,input:{userId:string; promotionRequestId:string}):Promise<PromotionRequestRow>{ const row=await single(client.from("pandora_promotion_requests").select("*").eq("user_id",input.userId).eq("id",input.promotionRequestId).limit(1)); if(!row) throw new Error("Promotion request not found for current user"); return row; }
export async function getPromotionRequestByPreflight(client:PromotionRequestDbClient,input:{userId:string; preflightId:string}):Promise<PromotionRequestRow|null>{ return single(client.from("pandora_promotion_requests").select("*").eq("user_id",input.userId).eq("preflight_id",input.preflightId).limit(1)); }
export async function createPromotionRequestEvent(client:PromotionRequestDbClient,input:{userId:string; promotionRequestId:string; shadowPackId:string; preflightId:string; eventType:string; message:string; metadata?:Record<string,unknown>}):Promise<PromotionRequestEventRow|null>{ const row={id:randomUUID(),user_id:input.userId,promotion_request_id:input.promotionRequestId,shadow_pack_id:input.shadowPackId,preflight_id:input.preflightId,event_type:input.eventType,message:input.message,metadata:input.metadata??{},created_at:new Date().toISOString()}; return single(client.from("pandora_promotion_request_events").insert(row).select("*").single()); }
export async function buildPromotionRequestPlan(client:PromotionRequestDbClient,input:{userId:string; preflightId:string; requestId?:string}){ const preflight=await getShadowPackPreflight(client as any,{userId:input.userId,preflightId:input.preflightId}); assertNamespace(preflight.namespace); const shadow=await getShadowContextPack(client as any,{userId:input.userId,shadowPackId:preflight.shadow_pack_id}); if(shadow.id!==preflight.shadow_pack_id) throw new Error("Preflight shadow pack mismatch"); if(shadow.namespace!==preflight.namespace) throw new Error("Shadow pack and preflight namespace mismatch"); const currentMaster=await activeMaster(client,input.userId,preflight.namespace); if(currentMaster && currentMaster.namespace!==preflight.namespace) throw new Error("Active master namespace mismatch"); const risk=preflight.risk_summary ?? { status:"blocked", blockers:["risk summary unavailable"], warnings:[]}; const warnings=[...(Array.isArray(preflight.warnings)?preflight.warnings:[]),...(Array.isArray((risk as any).warnings)?(risk as any).warnings:[])]; const blockers:string[]=[]; if(preflight.status!=="approved_for_promotion") blockers.push("Preflight is not approved_for_promotion."); if((risk as any).status==="blocked") blockers.push("Preflight risk status is blocked."); if(!currentMaster && (risk as any).status==="blocked") blockers.push("Active master is missing while risk status is blocked."); if((risk as any).status==="high") warnings.push("Risk status is high; human review should be cautious."); if(["rejected","archived"].includes(String(shadow.status))) warnings.push(`Shadow pack status is ${shadow.status}; promotion execution remains unavailable.`); if(new Date(preflight.updated_at).getTime() < new Date(shadow.updated_at).getTime()) warnings.push("Preflight is older than the shadow pack update timestamp."); if((preflight.active_master_pack_id??null)!==(currentMaster?.id??null)) warnings.push("Active master id in preflight no longer matches current active master id."); const status:PromotionRequestStatus=blockers.length?"blocked":"draft"; const promotion_plan={ plan_version:"promotion_request_board_v1", namespace:preflight.namespace, shadow_pack_id:shadow.id, preflight_id:preflight.id, active_master_pack_id:preflight.active_master_pack_id, intended_operation:"replace_active_master_with_shadow_candidate", steps:["verify preflight is approved_for_promotion","verify active master still matches preflight active_master_pack_id","verify shadow pack still reviewed or ready_for_review","archive existing active master","create new active master from shadow candidate","write audit event","refresh dashboard verification"], required_checks:["same_user","same_namespace","preflight_approved","risk_not_blocked","active_master_unchanged","no_duplicate_active_master_after_promotion"], execution_available:false, blockers };
 const rollback_plan={ plan_version:"promotion_request_board_v1", rollback_available_after_future_promotion:true, steps:["identify newly promoted master","archive newly promoted master","restore previous active master","write rollback audit event","re-run verification"], rollback_execution_available:false };
 return { preflight, shadow, currentMaster, status, blockers, warnings:Array.from(new Set(warnings)), promotion_plan, rollback_plan, risk_snapshot:risk, diff_snapshot:preflight.diff_summary, request_id:input.requestId??randomUUID(), title:`Promotion request for ${preflight.namespace} shadow pack`, summary:`Human-approved promotion request only for shadow pack ${shadow.id}. Approval does not execute promotion.` };
}
export async function createOrRefreshPromotionRequest(client:PromotionRequestDbClient,input:{userId:string; preflightId:string; requestId?:string}):Promise<PromotionRequestRow>{ const built=await buildPromotionRequestPlan(client,input); const existing=await getPromotionRequestByPreflight(client,{userId:input.userId,preflightId:input.preflightId}); const now=new Date().toISOString(); const base={user_id:input.userId,request_id:existing?.request_id??built.request_id,namespace:built.preflight.namespace,shadow_pack_id:built.shadow.id,preflight_id:built.preflight.id,active_master_pack_id:built.preflight.active_master_pack_id,status:built.status,title:built.title,summary:built.summary,promotion_plan:built.promotion_plan,rollback_plan:built.rollback_plan,risk_snapshot:built.risk_snapshot,diff_snapshot:built.diff_snapshot,warnings:built.warnings,updated_at:now}; const row=existing?await single(client.from("pandora_promotion_requests").update(base).eq("user_id",input.userId).eq("id",existing.id).select("*").single()):await single(client.from("pandora_promotion_requests").insert({id:randomUUID(),...base,reviewer_notes:"",reviewer_decision:null,created_at:now,submitted_at:null,approved_at:null,blocked_at:built.status==="blocked"?now:null,archived_at:null}).select("*").single()); if(!row) throw new Error("Unable to create or refresh promotion request"); await createPromotionRequestEvent(client,{userId:input.userId,promotionRequestId:row.id,shadowPackId:built.shadow.id,preflightId:built.preflight.id,eventType:existing?"promotion_request_refreshed":"promotion_request_created",message:"Promotion request prepared only; no promotion or core memory mutation performed.",metadata:{blockers:built.blockers,promotion_execution_available:false,no_core_memory_mutation_performed:true,no_promotion_performed:true}}); return row; }
export async function submitPromotionRequest(client:PromotionRequestDbClient,input:{userId:string; promotionRequestId:string}):Promise<PromotionRequestRow>{ const row=await getPromotionRequest(client,input); if(row.status!=="draft") throw new Error("Only draft promotion requests can be submitted"); const built=await buildPromotionRequestPlan(client,{userId:input.userId,preflightId:row.preflight_id,requestId:row.request_id}); if(built.blockers.length) throw new Error(`Promotion request has blockers: ${built.blockers.join("; ")}`); const now=new Date().toISOString(); const updated=await single(client.from("pandora_promotion_requests").update({status:"submitted",submitted_at:now,updated_at:now,warnings:built.warnings,promotion_plan:built.promotion_plan,rollback_plan:built.rollback_plan,risk_snapshot:built.risk_snapshot,diff_snapshot:built.diff_snapshot}).eq("user_id",input.userId).eq("id",input.promotionRequestId).select("*").single()); if(!updated) throw new Error("Unable to submit promotion request"); await createPromotionRequestEvent(client,{userId:input.userId,promotionRequestId:row.id,shadowPackId:row.shadow_pack_id,preflightId:row.preflight_id,eventType:"promotion_request_submitted",message:"Promotion request submitted for human review only; no promotion performed.",metadata:{no_promotion_performed:true}}); return updated; }
export async function updatePromotionRequestReview(client:PromotionRequestDbClient,input:{userId:string; promotionRequestId:string; reviewerNotes:string; reviewerDecision:string}):Promise<PromotionRequestRow>{ assertDecision(input.reviewerDecision); const row=await getPromotionRequest(client,input); if(!["draft","submitted"].includes(row.status)) throw new Error(`Cannot review promotion request in status ${row.status}`); const now=new Date().toISOString(); let status:PromotionRequestStatus=row.status; const patch:any={reviewer_notes:input.reviewerNotes??"",reviewer_decision:input.reviewerDecision,updated_at:now}; if(input.reviewerDecision==="approved"){ if(row.status!=="submitted") throw new Error("Only submitted promotion requests can be approved"); const built=await buildPromotionRequestPlan(client,{userId:input.userId,preflightId:row.preflight_id,requestId:row.request_id}); if(built.preflight.status!=="approved_for_promotion"||built.blockers.length) throw new Error("Approved review requires approved_for_promotion preflight with no blockers"); status="approved"; Object.assign(patch,{status,approved_at:now,warnings:built.warnings,promotion_plan:built.promotion_plan,rollback_plan:built.rollback_plan,risk_snapshot:built.risk_snapshot,diff_snapshot:built.diff_snapshot}); } else if(input.reviewerDecision==="blocked"){ status="blocked"; Object.assign(patch,{status,blocked_at:now}); }
 const updated=await single(client.from("pandora_promotion_requests").update(patch).eq("user_id",input.userId).eq("id",input.promotionRequestId).select("*").single()); if(!updated) throw new Error("Unable to save promotion request review"); await createPromotionRequestEvent(client,{userId:input.userId,promotionRequestId:row.id,shadowPackId:row.shadow_pack_id,preflightId:row.preflight_id,eventType:"promotion_request_reviewed",message:"Promotion request review saved. Approval is not execution and no promotion was performed.",metadata:{reviewer_decision:input.reviewerDecision,no_promotion_performed:true,no_core_memory_mutation_performed:true}}); return updated; }
export async function archivePromotionRequest(client:PromotionRequestDbClient,input:{userId:string; promotionRequestId:string; reason?:string}):Promise<PromotionRequestRow>{ const row=await getPromotionRequest(client,input); const now=new Date().toISOString(); const updated=await single(client.from("pandora_promotion_requests").update({status:"archived",archived_at:now,updated_at:now}).eq("user_id",input.userId).eq("id",input.promotionRequestId).select("*").single()); if(!updated) throw new Error("Unable to archive promotion request"); await createPromotionRequestEvent(client,{userId:input.userId,promotionRequestId:row.id,shadowPackId:row.shadow_pack_id,preflightId:row.preflight_id,eventType:"promotion_request_archived",message:input.reason?`Promotion request archived: ${input.reason}`:"Promotion request archived. No promotion performed.",metadata:{no_promotion_performed:true,no_core_memory_mutation_performed:true}}); return updated; }
