/* eslint-disable @typescript-eslint/no-explicit-any */
import { randomUUID } from "node:crypto";
import type { PandoraNamespace } from "@/components/pandora/types";
import { getShadowContextPack } from "@/lib/services/pandora-shadow-context-pack-service";

export type ShadowPackPreflightDbClient = { from: (table: string) => any };
export type ShadowPackPreflightStatus = "draft" | "ready_for_review" | "reviewed" | "approved_for_promotion" | "blocked" | "archived";
export type ShadowPackReviewerDecision = "needs_changes" | "approved_for_promotion" | "blocked";
export type ShadowPackRiskStatus = "low" | "medium" | "high" | "blocked";
export type ShadowPackDiffSummary = { active_master_pack_id: string | null; shadow_pack_id: string; namespace: PandoraNamespace; added_keys: string[]; removed_keys: string[]; changed_keys: string[]; unchanged_keys: string[]; source_event_count_delta: number; open_loop_count_delta: number; needs_review_count_delta: number; top_recent_summary_count: number; evidence_summary_changed: boolean; has_active_master: boolean; generated_at: string };
export type ShadowPackRiskSummary = { status: ShadowPackRiskStatus; score: number; reasons: string[]; blockers: string[]; warnings: string[] };
export type ShadowPackPreflightRow = { id: string; user_id: string; shadow_pack_id: string; namespace: PandoraNamespace; active_master_pack_id: string | null; request_id: string; status: ShadowPackPreflightStatus; diff_summary: ShadowPackDiffSummary; risk_summary: ShadowPackRiskSummary; reviewer_notes: string; reviewer_decision: ShadowPackReviewerDecision | null; warnings: string[]; created_at: string; updated_at: string; reviewed_at?: string | null; approved_for_promotion_at?: string | null; blocked_at?: string | null };
export type ShadowPackPreflightEventRow = { id: string; user_id: string; preflight_id: string; shadow_pack_id: string; event_type: string; message: string; metadata: Record<string, unknown>; created_at: string };

const NAMESPACES = new Set(["real_life", "au"]); const STATUSES = new Set(["draft", "ready_for_review", "reviewed", "approved_for_promotion", "blocked", "archived"]); const DECISIONS = new Set(["needs_changes", "approved_for_promotion", "blocked"]);
function assertNamespace(v: string): asserts v is PandoraNamespace { if (!NAMESPACES.has(v)) throw new Error(`Unsupported Pandora namespace: ${v}`); }
function assertStatus(v: string): asserts v is ShadowPackPreflightStatus { if (!STATUSES.has(v)) throw new Error(`Unsupported preflight status: ${v}`); }
function assertDecision(v: string): asserts v is ShadowPackReviewerDecision { if (!DECISIONS.has(v)) throw new Error(`Unsupported reviewer_decision: ${v}`); }
async function single(q: any) { const r = await q; if (r.error) return null; return Array.isArray(r.data) ? r.data[0] ?? null : r.data ?? null; }
function stable(v: unknown): string { if (Array.isArray(v)) return `[${v.map(stable).join(",")}]`; if (v && typeof v === "object") return `{${Object.keys(v as any).sort().map((k) => `${JSON.stringify(k)}:${stable((v as any)[k])}`).join(",")}}`; return JSON.stringify(v); }
function num(v: unknown) { const n = typeof v === "number" ? v : typeof v === "string" ? Number(v) : 0; return Number.isFinite(n) ? n : 0; }
function packPayload(row: any) { const out: Record<string, unknown> = row?.candidate_payload && typeof row.candidate_payload === "object" ? { ...row.candidate_payload } : {}; for (const k of ["namespace","summary","source_event_count","active_master_pack_id","top_recent_summaries","open_loop_count","needs_review_count","evidence_summary"]) if (row && k in row && !(k in out)) out[k] = row[k]; return out; }
function comparable(row: any, shadowPackId?: string) { const p = packPayload(row); const top = Array.isArray(p.top_recent_summaries) ? p.top_recent_summaries : Array.isArray(row?.top_recent_summaries) ? row.top_recent_summaries : []; const base: Record<string, unknown> = { summary: String(p.summary ?? row?.summary ?? ""), source_event_count: num(p.source_event_count ?? row?.source_event_count), active_master_pack_id: p.active_master_pack_id ?? row?.active_master_pack_id ?? row?.id ?? null, top_recent_summaries: top, open_loop_count: num(p.open_loop_count ?? row?.open_loop_count), needs_review_count: num(p.needs_review_count ?? row?.needs_review_count), evidence_summary: p.evidence_summary ?? row?.evidence_summary ?? null, candidate_payload_keys: Object.keys(p).sort(), shadow_pack_id: shadowPackId ?? row?.id ?? null, namespace: p.namespace ?? row?.namespace ?? null }; for (const [k, v] of Object.entries(p)) base[`candidate_payload.${k}`] = v; for (const [k, v] of Object.entries(row ?? {})) if (!["id","user_id","request_id","operator_action_id","created_at","updated_at","pack_type","status","title","summary","namespace","source_window","candidate_payload","evidence","warnings","reviewed_at","rejected_at","archived_at","source_event_count","open_loop_count","needs_review_count","top_recent_summaries","evidence_summary"].includes(k) && !(k in p)) base[`row.${k}`] = v; return base; }
async function activeMaster(client: ShadowPackPreflightDbClient, userId: string, namespace: PandoraNamespace) { return single(client.from("memory_context_packs").select("*").eq("user_id", userId).eq("namespace", namespace).eq("pack_type", "master").eq("status", "active").limit(1)); }
export async function computeShadowPackPreflight(client: ShadowPackPreflightDbClient, input: { userId: string; shadowPackId: string; requestId?: string }) { const shadow = await getShadowContextPack(client as any, { userId: input.userId, shadowPackId: input.shadowPackId }); assertNamespace(shadow.namespace); const master = await activeMaster(client, input.userId, shadow.namespace); const s = comparable(shadow, shadow.id); const m = master ? comparable(master) : {}; const keys = Array.from(new Set([...Object.keys(s), ...Object.keys(m)])).filter((k)=>!["shadow_pack_id"].includes(k)).sort(); const added = keys.filter((k)=>!(k in m)); const removed = keys.filter((k)=>k in m && !(k in s)); const changed = keys.filter((k)=>k in m && k in s && stable((m as any)[k]) !== stable((s as any)[k])); const unchanged = keys.filter((k)=>k in m && k in s && stable((m as any)[k]) === stable((s as any)[k])); const warnings: string[] = [];
  if (!Array.isArray((s as any).top_recent_summaries) || (s as any).top_recent_summaries.length === 0) warnings.push("top_recent_summaries are empty; preflight cannot infer semantic quality."); if (!(s as any).evidence_summary) warnings.push("evidence_summary missing; preflight remains deterministic and warning-backed.");
  const blockers: string[] = []; if (!master) blockers.push("No active master context pack exists for this user and namespace."); if (master && master.namespace !== shadow.namespace) blockers.push("Shadow namespace and active master namespace mismatch."); const diff: ShadowPackDiffSummary = { active_master_pack_id: master?.id ?? null, shadow_pack_id: shadow.id, namespace: shadow.namespace, added_keys: added, removed_keys: removed, changed_keys: changed, unchanged_keys: unchanged, source_event_count_delta: num((s as any).source_event_count)-num((m as any).source_event_count), open_loop_count_delta: num((s as any).open_loop_count)-num((m as any).open_loop_count), needs_review_count_delta: num((s as any).needs_review_count)-num((m as any).needs_review_count), top_recent_summary_count: Array.isArray((s as any).top_recent_summaries)?(s as any).top_recent_summaries.length:0, evidence_summary_changed: stable((s as any).evidence_summary)!==stable((m as any).evidence_summary), has_active_master: Boolean(master), generated_at: new Date().toISOString() };
  let status: ShadowPackRiskStatus = "low"; let score = 10; const reasons: string[] = [];
  if (blockers.length) { status = "blocked"; score = 100; reasons.push("Promotion preflight blocked until a comparable active master is available."); }
  else if (diff.source_event_count_delta > 500 || diff.removed_keys.length > 0) { status = "high"; score = 80; reasons.push("Large source-event delta or removed comparable keys detected."); }
  else if (diff.changed_keys.length > 8 || diff.open_loop_count_delta > 20) { status = "medium"; score = 50; reasons.push("Moderate deterministic change volume detected."); }
  else { reasons.push("Active master exists, no removed keys, and changed key count is within the low-risk threshold."); }
  const risk: ShadowPackRiskSummary = { status, score, reasons, blockers, warnings };
  const preflightStatus: ShadowPackPreflightStatus = status === "blocked" ? "blocked" : warnings.length ? "draft" : "ready_for_review";
  return { shadow, activeMaster: master, diff_summary: diff, risk_summary: risk, warnings, status: preflightStatus, request_id: input.requestId ?? randomUUID() };
}
export async function listShadowPackPreflights(client: ShadowPackPreflightDbClient, input: { userId: string; namespace?: string; status?: string; limit?: number }): Promise<ShadowPackPreflightRow[]> { if(input.namespace) assertNamespace(input.namespace); if(input.status) assertStatus(input.status); let q=client.from("pandora_shadow_pack_preflights").select("*").eq("user_id",input.userId).order("created_at",{ascending:false}).limit(input.limit??20); if(input.namespace) q=q.eq("namespace",input.namespace); if(input.status) q=q.eq("status",input.status); const r=await q; return r.error?[]:(Array.isArray(r.data)?r.data:[]); }
export async function getShadowPackPreflight(client: ShadowPackPreflightDbClient, input:{userId:string; preflightId:string}): Promise<ShadowPackPreflightRow>{ const row=await single(client.from("pandora_shadow_pack_preflights").select("*").eq("user_id",input.userId).eq("id",input.preflightId).limit(1)); if(!row) throw new Error("Shadow pack preflight not found for current user"); return row; }
export async function getShadowPackPreflightByShadowPack(client: ShadowPackPreflightDbClient, input:{userId:string; shadowPackId:string}){ return single(client.from("pandora_shadow_pack_preflights").select("*").eq("user_id",input.userId).eq("shadow_pack_id",input.shadowPackId).limit(1)); }
export async function createShadowPackPreflightEvent(client: ShadowPackPreflightDbClient, input:{userId:string; preflightId:string; shadowPackId:string; eventType:string; message:string; metadata?:Record<string,unknown>}): Promise<ShadowPackPreflightEventRow|null>{ const row={id:randomUUID(),user_id:input.userId,preflight_id:input.preflightId,shadow_pack_id:input.shadowPackId,event_type:input.eventType,message:input.message,metadata:input.metadata??{},created_at:new Date().toISOString()}; return single(client.from("pandora_shadow_pack_preflight_events").insert(row).select("*").single()); }
export async function createOrRefreshShadowPackPreflight(client: ShadowPackPreflightDbClient, input:{userId:string; shadowPackId:string; requestId?:string}): Promise<ShadowPackPreflightRow>{ const built=await computeShadowPackPreflight(client,input); const existing=await getShadowPackPreflightByShadowPack(client,{userId:input.userId,shadowPackId:input.shadowPackId}); const now=new Date().toISOString(); const base={user_id:input.userId,shadow_pack_id:input.shadowPackId,namespace:built.shadow.namespace,active_master_pack_id:built.activeMaster?.id??null,request_id:built.request_id,status:built.status,diff_summary:built.diff_summary,risk_summary:built.risk_summary,warnings:built.warnings,updated_at:now}; const row=existing? await single(client.from("pandora_shadow_pack_preflights").update(base).eq("user_id",input.userId).eq("id",existing.id).select("*").single()) : await single(client.from("pandora_shadow_pack_preflights").insert({id:randomUUID(),...base,reviewer_notes:"",reviewer_decision:null,created_at:now,reviewed_at:null,approved_for_promotion_at:null,blocked_at:built.status==="blocked"?now:null}).select("*").single()); if(!row) throw new Error("Unable to create or refresh shadow pack preflight"); await createShadowPackPreflightEvent(client,{userId:input.userId,preflightId:row.id,shadowPackId:input.shadowPackId,eventType:existing?"preflight_refreshed":"preflight_created",message:"Shadow pack promotion preflight prepared. No production context pack mutation or promotion performed.",metadata:{risk_status:built.risk_summary.status,no_core_memory_mutation_performed:true,no_promotion_performed:true}}); return row; }
export async function updateShadowPackPreflightReview(client: ShadowPackPreflightDbClient, input:{userId:string; preflightId:string; reviewerNotes:string; reviewerDecision:string}): Promise<ShadowPackPreflightRow>{ assertDecision(input.reviewerDecision); const row=await getShadowPackPreflight(client,input); const now=new Date().toISOString(); const status:ShadowPackPreflightStatus=input.reviewerDecision==="approved_for_promotion"?"approved_for_promotion":input.reviewerDecision==="blocked"?"blocked":"reviewed"; const patch:any={reviewer_notes:input.reviewerNotes??"",reviewer_decision:input.reviewerDecision,status,reviewed_at:now,updated_at:now}; if(status==="approved_for_promotion") patch.approved_for_promotion_at=now; if(status==="blocked") patch.blocked_at=now; const updated=await single(client.from("pandora_shadow_pack_preflights").update(patch).eq("user_id",input.userId).eq("id",input.preflightId).select("*").single()); if(!updated) throw new Error("Unable to update preflight review"); await createShadowPackPreflightEvent(client,{userId:input.userId,preflightId:input.preflightId,shadowPackId:row.shadow_pack_id,eventType:"preflight_reviewed",message:"Reviewer decision saved for future promotion consideration only; no promotion performed.",metadata:{reviewer_decision:input.reviewerDecision,no_core_memory_mutation_performed:true,no_promotion_performed:true}}); return updated; }
export async function archiveShadowPackPreflight(client: ShadowPackPreflightDbClient, input:{userId:string; preflightId:string; reason?:string}): Promise<ShadowPackPreflightRow>{ const row=await getShadowPackPreflight(client,input); const updated=await single(client.from("pandora_shadow_pack_preflights").update({status:"archived",updated_at:new Date().toISOString()}).eq("user_id",input.userId).eq("id",input.preflightId).select("*").single()); if(!updated) throw new Error("Unable to archive preflight"); await createShadowPackPreflightEvent(client,{userId:input.userId,preflightId:input.preflightId,shadowPackId:row.shadow_pack_id,eventType:"preflight_archived",message:input.reason?`Preflight archived: ${input.reason}`:"Preflight archived. No core memory mutation performed.",metadata:{no_core_memory_mutation_performed:true,no_promotion_performed:true}}); return updated; }
