/* eslint-disable @typescript-eslint/no-explicit-any */
import { randomUUID } from "node:crypto";
import type { PandoraNamespace } from "@/components/pandora/types";
import { buildPromotionRequestPlan, getPromotionRequest, createPromotionRequestEvent, type PromotionRequestDbClient, type PromotionRequestRow } from "@/lib/services/pandora-promotion-request-service";

// Promotion executor v1. Execution is double-gated: PANDORA_ENABLE_CONTEXT_PACK_PROMOTION
// must be "true" AND the promotion request must be human-approved with a fresh, blocker-free
// plan AND the caller must pass the explicit confirmation phrase. Promotion is status-only on
// memory_context_packs (insert new master from the reviewed shadow candidate, archive the old
// master). Nothing is ever deleted; memory_events, memory_items, memory_profiles, capture and
// pruning candidates are never touched. Rollback restores the previous master the same way.

export type PromotionExecutionDbClient = PromotionRequestDbClient;
export type PromotionExecutionMode = "execute" | "rollback";
export type PromotionExecutionStatus = "executed" | "rolled_back" | "blocked" | "failed";
export type PromotionExecutionRow = { id:string; user_id:string; request_id:string; namespace:PandoraNamespace; promotion_request_id:string; preflight_id:string; shadow_pack_id:string; previous_master_pack_id:string|null; promoted_pack_id:string|null; mode:PromotionExecutionMode; status:PromotionExecutionStatus; plan:Record<string,unknown>; result:Record<string,unknown>; warnings:string[]; created_at:string; updated_at:string; executed_at?:string|null; rolled_back_at?:string|null };

export const PROMOTION_EXECUTION_GATE = "PANDORA_ENABLE_CONTEXT_PACK_PROMOTION";
export const PROMOTE_CONFIRMATION = "PROMOTE";
export const ROLLBACK_CONFIRMATION = "ROLLBACK";
export function isPromotionExecutionEnabled(env: Partial<NodeJS.ProcessEnv> = process.env): boolean { return env[PROMOTION_EXECUTION_GATE] === "true"; }

async function single(q:any){ const r=await q; if(r.error) return null; return Array.isArray(r.data)?r.data[0]??null:r.data??null; }
async function audit(client:PromotionExecutionDbClient,input:{userId:string; namespace:PandoraNamespace; action:string; recordId:string; metadata:Record<string,unknown>}){ await client.from("audit_logs").insert({ user_id:input.userId, namespace:input.namespace, action:input.action, table_name:"memory_context_packs", record_id:input.recordId, after_snapshot:input.metadata, metadata:{...input.metadata, phase:"promotion_executor_v1", appendOnly:true} }).select("*").single(); }
async function createExecutionEvent(client:PromotionExecutionDbClient,input:{userId:string; executionId:string; promotionRequestId:string; eventType:string; message:string; metadata?:Record<string,unknown>}){ await client.from("pandora_promotion_execution_events").insert({ id:randomUUID(), user_id:input.userId, execution_id:input.executionId, promotion_request_id:input.promotionRequestId, event_type:input.eventType, message:input.message, metadata:input.metadata??{}, created_at:new Date().toISOString() }).select("*").single(); }
async function insertExecutionRow(client:PromotionExecutionDbClient,row:Omit<PromotionExecutionRow,"created_at"|"updated_at"> & {created_at?:string; updated_at?:string}):Promise<PromotionExecutionRow>{ const now=new Date().toISOString(); const created=await single(client.from("pandora_promotion_executions").insert({...row,created_at:row.created_at??now,updated_at:row.updated_at??now}).select("*").single()); if(!created) throw new Error("Unable to record promotion execution"); return created; }

export async function listPromotionExecutions(client:PromotionExecutionDbClient,input:{userId:string; limit?:number}):Promise<PromotionExecutionRow[]>{ const r=await client.from("pandora_promotion_executions").select("*").eq("user_id",input.userId).order("created_at",{ascending:false}).limit(input.limit??20); return r.error?[]:(Array.isArray(r.data)?r.data:[]); }
export async function getPromotionExecution(client:PromotionExecutionDbClient,input:{userId:string; executionId:string}):Promise<PromotionExecutionRow>{ const row=await single(client.from("pandora_promotion_executions").select("*").eq("user_id",input.userId).eq("id",input.executionId).limit(1)); if(!row) throw new Error("Promotion execution not found for current user"); return row; }

// Pure compute. Re-derives the plan from live preflight/shadow/master state and adds the
// execution-stage blockers on top of the request-stage ones. Performs no writes.
export async function buildPromotionExecutionPlan(client:PromotionExecutionDbClient,input:{userId:string; promotionRequestId:string}){ const request:PromotionRequestRow=await getPromotionRequest(client,input); const built=await buildPromotionRequestPlan(client,{userId:input.userId,preflightId:request.preflight_id,requestId:request.request_id}); const blockers=[...built.blockers]; const warnings=[...built.warnings]; if(request.status!=="approved") blockers.push(`Promotion request status is ${request.status}; only approved requests can execute.`); if(request.reviewer_decision!=="approved") blockers.push("Promotion request has no approved reviewer decision."); if(["rejected","archived"].includes(String(built.shadow.status))) blockers.push(`Shadow pack status is ${built.shadow.status}; execution refused.`); const liveMasterId=built.currentMaster?.id??null; if((request.active_master_pack_id??null)!==liveMasterId) blockers.push("Active master changed since approval; re-run preflight and re-approve before executing."); const plan={ plan_version:"promotion_executor_v1", namespace:request.namespace, promotion_request_id:request.id, preflight_id:request.preflight_id, shadow_pack_id:request.shadow_pack_id, previous_master_pack_id:liveMasterId, operation:"archive_active_master_then_insert_shadow_candidate_as_master", status_only:true, never_deletes:true, tables_touched:["memory_context_packs","pandora_promotion_requests","pandora_promotion_executions","pandora_promotion_execution_events","pandora_promotion_request_events","audit_logs"], blockers }; return { request, built, blockers, warnings:Array.from(new Set(warnings)), plan, previousMasterId:liveMasterId }; }

export async function dryRunPromotionExecution(client:PromotionExecutionDbClient,input:{userId:string; promotionRequestId:string},env:Partial<NodeJS.ProcessEnv>=process.env){ const computed=await buildPromotionExecutionPlan(client,input); return { mode:"dry_run" as const, gate_enabled:isPromotionExecutionEnabled(env), executable:computed.blockers.length===0&&isPromotionExecutionEnabled(env), blockers:computed.blockers, warnings:computed.warnings, plan:computed.plan, no_core_memory_mutation_performed:true, no_promotion_performed:true }; }

function packFromShadowCandidate(shadow:{id:string; namespace:PandoraNamespace; title:string; summary:string; candidate_payload:Record<string,unknown>}, userId:string){ const p=shadow.candidate_payload??{}; const arr=(v:unknown)=>Array.isArray(v)?v:[]; return { id:randomUUID(), user_id:userId, namespace:shadow.namespace, pack_type:"master", status:"active", title:typeof p.title==="string"&&p.title?p.title:shadow.title, summary:typeof p.summary==="string"&&p.summary?p.summary:shadow.summary, key_points:arr(p.key_points), active_projects:arr(p.active_projects), people_map:arr(p.people_map), decisions:arr(p.decisions), risks:arr(p.risks), open_loops:arr(p.open_loops), generated_from_event_ids:arr(p.generated_from_event_ids), created_at:new Date().toISOString(), updated_at:new Date().toISOString() }; }

export async function executeApprovedPromotion(client:PromotionExecutionDbClient,input:{userId:string; promotionRequestId:string; confirmation:string},env:Partial<NodeJS.ProcessEnv>=process.env):Promise<PromotionExecutionRow>{
  if(input.confirmation!==PROMOTE_CONFIRMATION) throw new Error(`Execution requires the explicit confirmation phrase "${PROMOTE_CONFIRMATION}".`);
  if(!isPromotionExecutionEnabled(env)) throw new Error(`promotion_execution_disabled: set ${PROMOTION_EXECUTION_GATE}=true after review to enable execution.`);
  const computed=await buildPromotionExecutionPlan(client,input); const { request }=computed; const now=new Date().toISOString();
  if(computed.blockers.length){ const blocked=await insertExecutionRow(client,{ id:randomUUID(), user_id:input.userId, request_id:request.request_id, namespace:request.namespace, promotion_request_id:request.id, preflight_id:request.preflight_id, shadow_pack_id:request.shadow_pack_id, previous_master_pack_id:computed.previousMasterId, promoted_pack_id:null, mode:"execute", status:"blocked", plan:computed.plan, result:{blockers:computed.blockers,no_core_memory_mutation_performed:true,no_promotion_performed:true}, warnings:computed.warnings }); await createExecutionEvent(client,{userId:input.userId,executionId:blocked.id,promotionRequestId:request.id,eventType:"promotion_execution_blocked",message:"Promotion execution blocked; no core memory mutation performed.",metadata:{blockers:computed.blockers}}); throw new Error(`Promotion execution blocked: ${computed.blockers.join("; ")}`); }
  const promoted=await single(client.from("memory_context_packs").insert(packFromShadowCandidate(computed.built.shadow,input.userId)).select("*").single()); if(!promoted) throw new Error("Promotion failed: unable to insert new master context pack. No archive was performed.");
  const archived=await (client.from("memory_context_packs").update({status:"archived",updated_at:now}).eq("user_id",input.userId).eq("namespace",request.namespace).eq("pack_type","master").eq("status","active").neq("id",promoted.id).select("id") as unknown as Promise<{data:unknown[]|null; error:{message:string}|null}>);
  const warnings=[...computed.warnings]; if(archived.error) warnings.push(`archive_previous_master_failed: ${archived.error.message}`);
  const updatedRequest=await single(client.from("pandora_promotion_requests").update({status:"promoted",updated_at:now}).eq("user_id",input.userId).eq("id",request.id).select("*").single()); if(!updatedRequest) warnings.push("promotion_request_status_update_failed");
  const execution=await insertExecutionRow(client,{ id:randomUUID(), user_id:input.userId, request_id:request.request_id, namespace:request.namespace, promotion_request_id:request.id, preflight_id:request.preflight_id, shadow_pack_id:request.shadow_pack_id, previous_master_pack_id:computed.previousMasterId, promoted_pack_id:promoted.id, mode:"execute", status:"executed", plan:computed.plan, result:{promoted_pack_id:promoted.id,previous_master_pack_id:computed.previousMasterId,archived_pack_ids:(archived.data??[]).map((r:any)=>r.id),status_only:true,never_deletes:true}, warnings, executed_at:now });
  await createExecutionEvent(client,{userId:input.userId,executionId:execution.id,promotionRequestId:request.id,eventType:"promotion_executed",message:"Shadow candidate promoted to active master. Previous master archived (status-only, reversible).",metadata:{promoted_pack_id:promoted.id,previous_master_pack_id:computed.previousMasterId}});
  await createPromotionRequestEvent(client,{userId:input.userId,promotionRequestId:request.id,shadowPackId:request.shadow_pack_id,preflightId:request.preflight_id,eventType:"promotion_executed",message:"Approved promotion request executed via gated executor.",metadata:{execution_id:execution.id,promoted_pack_id:promoted.id}});
  await audit(client,{userId:input.userId,namespace:request.namespace,action:"memory_context_pack_promoted",recordId:promoted.id,metadata:{execution_id:execution.id,promotion_request_id:request.id,previous_master_pack_id:computed.previousMasterId,status_only:true}});
  return execution;
}

export async function rollbackPromotionExecution(client:PromotionExecutionDbClient,input:{userId:string; executionId:string; confirmation:string},env:Partial<NodeJS.ProcessEnv>=process.env):Promise<PromotionExecutionRow>{
  if(input.confirmation!==ROLLBACK_CONFIRMATION) throw new Error(`Rollback requires the explicit confirmation phrase "${ROLLBACK_CONFIRMATION}".`);
  if(!isPromotionExecutionEnabled(env)) throw new Error(`promotion_execution_disabled: set ${PROMOTION_EXECUTION_GATE}=true after review to enable rollback.`);
  const execution=await getPromotionExecution(client,input); if(execution.mode!=="execute"||execution.status!=="executed") throw new Error(`Only executed promotions can be rolled back (found mode=${execution.mode}, status=${execution.status}).`); if(!execution.promoted_pack_id) throw new Error("Execution has no promoted pack to roll back.");
  const now=new Date().toISOString();
  const archivedPromoted=await single(client.from("memory_context_packs").update({status:"archived",updated_at:now}).eq("user_id",input.userId).eq("id",execution.promoted_pack_id).select("*").single()); if(!archivedPromoted) throw new Error("Rollback failed: promoted pack not found for current user.");
  const warnings:string[]=[];
  if(execution.previous_master_pack_id){ const restored=await single(client.from("memory_context_packs").update({status:"active",updated_at:now}).eq("user_id",input.userId).eq("id",execution.previous_master_pack_id).select("*").single()); if(!restored) warnings.push("restore_previous_master_failed"); } else warnings.push("no_previous_master_to_restore");
  const updated=await single(client.from("pandora_promotion_executions").update({status:"rolled_back",rolled_back_at:now,updated_at:now,warnings}).eq("user_id",input.userId).eq("id",execution.id).select("*").single()); if(!updated) throw new Error("Unable to record rollback on execution row");
  await createExecutionEvent(client,{userId:input.userId,executionId:execution.id,promotionRequestId:execution.promotion_request_id,eventType:"promotion_rolled_back",message:"Promotion rolled back: promoted pack archived, previous master restored (status-only, reversible).",metadata:{promoted_pack_id:execution.promoted_pack_id,previous_master_pack_id:execution.previous_master_pack_id}});
  await audit(client,{userId:input.userId,namespace:execution.namespace,action:"memory_context_pack_promotion_rolled_back",recordId:execution.promoted_pack_id,metadata:{execution_id:execution.id,previous_master_pack_id:execution.previous_master_pack_id,status_only:true}});
  return updated;
}
