/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { approveCandidateForReview, captureApprovedCandidate, editCandidateForReview, markCandidateDuplicate, type MemoryCaptureCandidate } from "../lib/services/memory-candidate-service";
import { listMemoryCandidatesForAdmin } from "../lib/services/admin-memory-candidate-loader";

function client(seed: Partial<Record<string, any[]>>) {
  const rows: Record<string, any[]> = { memory_capture_candidates: [], memory_events: [], memory_feedback_events: [], ...seed };
  return { rows, from(table: string) { let selected = [...(rows[table] ?? [])]; let patch: any; let insertValue: any; const api: any = { select: () => api, eq: (k: string, v: any) => { selected = selected.filter((r) => r[k] === v); return api; }, order: (k: string, opt: any) => { selected.sort((a,b)=> opt?.ascending ? String(a[k]).localeCompare(String(b[k])) : String(b[k]).localeCompare(String(a[k]))); return api; }, limit: (n: number) => { selected = selected.slice(0,n); return api; }, update: (v: any) => { patch = v; return api; }, insert: (v: any) => { insertValue = v; return api; }, single: async () => { if (insertValue) { const row = { id: `${table}-${rows[table].length + 1}`, ...insertValue }; rows[table].push(row); return { data: row, error: null }; } const row = selected[0]; if (!row) return { data: null, error: { message: "not found" } }; if (patch) Object.assign(row, patch); return { data: row, error: null }; }, then: (resolve: any) => resolve({ data: selected, error: null }) }; return api; } } as any;
}
const cand = (over: Partial<MemoryCaptureCandidate> = {}): MemoryCaptureCandidate => ({ id: "c1", user_id: "u1", namespace: "real_life", source: "turn", redacted_excerpt: "Project X deadline moved", memory_type: "project", title: "Project X", summary: "Project X deadline moved", importance: 7, sensitivity: "medium", confidence: 0.9, should_capture: true, requires_review: true, status: "pending", reason: "durable", tags: [], risks: [], people: [], projects: [], metadata: {}, created_at: "2026-01-01", ...over });

describe("Phase 5B candidate review service", () => {
  it("approves pending candidates and writes feedback", async () => { const c = client({ memory_capture_candidates: [cand()] }); const r = await approveCandidateForReview(c, { id: "c1", userId: "u1", namespace: "real_life" }); expect(r.ok).toBe(true); expect(c.rows.memory_capture_candidates[0].status).toBe("approved"); expect(c.rows.memory_feedback_events[0].action).toBe("approve"); });
  it("blocks blocked_secret approval and capture", async () => { const c = client({ memory_capture_candidates: [cand({ status: "blocked_secret" })] }); expect((await approveCandidateForReview(c, { id: "c1", userId: "u1", namespace: "real_life" })).blockers).toContain("blocked_secret_cannot_be_approved"); expect((await captureApprovedCandidate(c, { id: "c1", userId: "u1", namespace: "real_life" })).blockers).toContain("blocked_secret_cannot_be_captured"); });
  it("blocks rejected, duplicate, and non-approved capture", async () => { for (const status of ["rejected", "duplicate", "pending"] as const) { const c = client({ memory_capture_candidates: [cand({ status })] }); const r = await captureApprovedCandidate(c, { id: "c1", userId: "u1", namespace: "real_life" }); expect(r.ok).toBe(false); } });
  it("captures approved candidates and updates captured_event_id", async () => { const c = client({ memory_capture_candidates: [cand({ status: "approved" })] }); const r = await captureApprovedCandidate(c, { id: "c1", userId: "u1", namespace: "real_life" }); expect(r.ok).toBe(true); expect(c.rows.memory_events).toHaveLength(1); expect(c.rows.memory_capture_candidates[0].status).toBe("captured"); expect(c.rows.memory_capture_candidates[0].captured_event_id).toBeTruthy(); expect(c.rows.memory_feedback_events[0].action).toBe("capture"); });
  it("scopes by user and namespace", async () => { const c = client({ memory_capture_candidates: [cand({ user_id: "other" })] }); const r = await approveCandidateForReview(c, { id: "c1", userId: "u1", namespace: "real_life" }); expect(r.ok).toBe(false); expect(r.blockers).toContain("candidate_not_found"); });
  it("edit blocks secret content and duplicate marks status", async () => { const c = client({ memory_capture_candidates: [cand()] }); const secretEdit = await editCandidateForReview(c, { id:"c1", userId:"u1", namespace:"real_life", title:"t", summary:"password=abc123456789", memory_type:"note", sensitivity:"private", importance:5 }); expect(secretEdit.ok).toBe(false); expect(c.rows.memory_capture_candidates[0].status).toBe("blocked_secret"); const d = client({ memory_capture_candidates: [cand()] }); expect((await markCandidateDuplicate(d, { id:"c1", userId:"u1", namespace:"real_life" })).ok).toBe(true); expect(d.rows.memory_capture_candidates[0].status).toBe("duplicate"); });
});

describe("Phase 5B loader", () => {
  it("defaults to pending, respects namespace/status, returns counts, caps limit, and redacts blocked secrets", async () => { const c = client({ memory_capture_candidates: [cand(), cand({ id:"c2", status:"blocked_secret", raw_excerpt:"secret", namespace:"au" }), cand({ id:"c3", status:"approved" })] }); const r = await listMemoryCandidatesForAdmin(c, { userId:"u1", filters:{ limit:999 } }); expect(r.candidates).toHaveLength(1); expect(r.counts.total).toBe(3); expect(r.warnings).toContain("limit_capped_at_100"); const blocked = await listMemoryCandidatesForAdmin(c, { userId:"u1", filters:{ namespace:"au", status:"blocked_secret" } }); expect(blocked.candidates[0].raw_excerpt).toBe("[REDACTED_SECRET]"); });
});
