"use server";
import { revalidatePath } from "next/cache";
import { resolvePandoraRuntimeSafetyConfig } from "@/lib/config/pandora-runtime-safety-config";
import { resolvePandoraServerSession } from "@/lib/auth/pandora-server-session-resolver";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { MemoryBridgeDbClient, MemoryBridgeNamespace } from "@/lib/services/memory-bridge-service";
import { approveCandidateForReview, captureApprovedCandidate, editCandidateForReview, markCandidateDuplicate, rejectCandidateForReview, type MemorySensitivity } from "@/lib/services/memory-candidate-service";
const ns = (v: FormDataEntryValue | null): MemoryBridgeNamespace => v === "au" ? "au" : "real_life";
async function ctx(formData: FormData) { const runtime = resolvePandoraRuntimeSafetyConfig(); if (!runtime.config.memoryCaptureApiEnabled) throw new Error("memoryCaptureApiEnabled_disabled"); const session = await resolvePandoraServerSession(); if (!session.ok) throw new Error("auth_required"); return { userId: session.session.userId, client: (await createSupabaseServerClient()) as unknown as MemoryBridgeDbClient, id: String(formData.get("id") ?? ""), namespace: ns(formData.get("namespace")) }; }
export async function approveCandidateAction(formData: FormData) { const c = await ctx(formData); await approveCandidateForReview(c.client, { ...c, review_note: String(formData.get("review_note") ?? "") }); revalidatePath("/admin/memory/candidates"); }
export async function rejectCandidateAction(formData: FormData) { const c = await ctx(formData); await rejectCandidateForReview(c.client, { ...c, reason: String(formData.get("reason") ?? "other"), review_note: String(formData.get("review_note") ?? "") }); revalidatePath("/admin/memory/candidates"); }
export async function duplicateCandidateAction(formData: FormData) { const c = await ctx(formData); await markCandidateDuplicate(c.client, { ...c, duplicate_of_candidate_id: String(formData.get("duplicate_of_candidate_id") ?? "") || undefined, review_note: String(formData.get("review_note") ?? "") }); revalidatePath("/admin/memory/candidates"); }
export async function captureCandidateAction(formData: FormData) { const c = await ctx(formData); await captureApprovedCandidate(c.client, c); revalidatePath("/admin/memory/candidates"); }
export async function editCandidateAction(formData: FormData) { const c = await ctx(formData); await editCandidateForReview(c.client, { ...c, title: String(formData.get("title") ?? ""), summary: String(formData.get("summary") ?? ""), memory_type: String(formData.get("memory_type") ?? "note"), sensitivity: String(formData.get("sensitivity") ?? "medium") as MemorySensitivity, importance: Number(formData.get("importance") ?? 5), tags: String(formData.get("tags") ?? "").split(",").map((s)=>s.trim()).filter(Boolean), risks: String(formData.get("risks") ?? "").split(",").map((s)=>s.trim()).filter(Boolean), people: String(formData.get("people") ?? "").split(",").map((s)=>s.trim()).filter(Boolean), projects: String(formData.get("projects") ?? "").split(",").map((s)=>s.trim()).filter(Boolean) }); revalidatePath("/admin/memory/candidates"); }
