/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { archiveShadowPackPreflight, computeShadowPackPreflight, createOrRefreshShadowPackPreflight, updateShadowPackPreflightReview } from "@/lib/services/pandora-shadow-pack-preflight-service";
const USER="11111111-1111-4111-8111-111111111111", OTHER="22222222-2222-4222-8222-222222222222";
type Store=Record<string, any[]>;
function client(store:Store){ return { from(table:string){ const eqs:Record<string,any>={}; let lim=Infinity; let patch:any; let inserted:any; const rows=()=> (store[table]??[]).filter(r=>Object.entries(eqs).every(([k,v])=>r[k]===v)).slice(0,lim); const b:any={ select(){return b}, eq(k:string,v:any){eqs[k]=v;return b}, order(){return b}, limit(n:number){lim=n;return b}, single(){return b}, insert(row:any){inserted=Array.isArray(row)?row[0]:row; store[table]=store[table]??[]; store[table].push(inserted); return b}, update(row:any){patch=row; return b}, then(res:any,rej:any){ if(patch){ const r=rows()[0]; if(r) Object.assign(r,patch); return Promise.resolve({data:r??null,error:r?null:{message:"missing"}}).then(res,rej)} return Promise.resolve({data:inserted??rows(),error:null}).then(res,rej)}}; return b; }} as any; }
function shadow(payload:any={}){return { id:"s1", user_id:USER, request_id:"req", namespace:"real_life", pack_type:"master_candidate", status:"ready_for_review", title:"S", summary:"shadow", source_window:{}, candidate_payload:{ namespace:"real_life", source_event_count:10, open_loop_count:1, needs_review_count:1, top_recent_summaries:["a"], evidence_summary:"evidence", ...payload }, evidence:{}, warnings:[], created_at:"now", updated_at:"now"};}
function store():Store{return { pandora_shadow_context_packs:[shadow()], pandora_shadow_pack_preflights:[], pandora_shadow_pack_preflight_events:[], memory_context_packs:[{id:"m1",user_id:USER,namespace:"real_life",pack_type:"master",status:"active",summary:"master",source_event_count:9,open_loop_count:1,needs_review_count:1,top_recent_summaries:["a"],evidence_summary:"evidence",created_at:"now"}], memory_events:[]};}
describe("shadow pack preflight service",()=>{
 it("creates and refreshes one own preflight without core writes", async()=>{const s=store(); const c=client(s); const a=await createOrRefreshShadowPackPreflight(c,{userId:USER,shadowPackId:"s1"}); const b=await createOrRefreshShadowPackPreflight(c,{userId:USER,shadowPackId:"s1"}); expect(a.id).toBe(b.id); expect(s.pandora_shadow_pack_preflights).toHaveLength(1); expect(s.memory_context_packs).toHaveLength(1); expect(s.memory_events).toHaveLength(0);});
 it("blocks cross-user shadow pack", async()=>{await expect(createOrRefreshShadowPackPreflight(client(store()),{userId:OTHER,shadowPackId:"s1"})).rejects.toThrow(/not found/);});
 it("active master missing is blocked", async()=>{const s=store(); s.memory_context_packs=[]; const r=await computeShadowPackPreflight(client(s),{userId:USER,shadowPackId:"s1"}); expect(r.risk_summary.status).toBe("blocked");});
 it("removed keys are high risk", async()=>{const s=store(); s.memory_context_packs[0].legacy_key="gone"; const r=await computeShadowPackPreflight(client(s),{userId:USER,shadowPackId:"s1"}); expect(r.risk_summary.status).toBe("high");});
 it("changed keys <= 8 are low and > 8 are medium", async()=>{let r=await computeShadowPackPreflight(client(store()),{userId:USER,shadowPackId:"s1"}); expect(r.risk_summary.status).toBe("low"); const s=store(); s.memory_context_packs[0].candidate_payload = { namespace:"real_life", source_event_count:10, open_loop_count:1, needs_review_count:1, top_recent_summaries:["a"], evidence_summary:"evidence", a:0,b:0,c:0,d:0,e:0,f:0,g:0,h:0,i:0 }; s.pandora_shadow_context_packs[0]=shadow({a:1,b:2,c:3,d:4,e:5,f:6,g:7,h:8,i:9}); r=await computeShadowPackPreflight(client(s),{userId:USER,shadowPackId:"s1"}); expect(r.risk_summary.status).toBe("medium");});
 it("source event delta over 500 is high", async()=>{const s=store(); s.pandora_shadow_context_packs[0]=shadow({source_event_count:600}); const r=await computeShadowPackPreflight(client(s),{userId:USER,shadowPackId:"s1"}); expect(r.risk_summary.status).toBe("high");});
 it("empty recent summaries and missing evidence warn", async()=>{const s=store(); s.pandora_shadow_context_packs[0]=shadow({top_recent_summaries:[], evidence_summary:null}); const r=await computeShadowPackPreflight(client(s),{userId:USER,shadowPackId:"s1"}); expect(r.warnings.join(" ")).toContain("top_recent_summaries"); expect(r.warnings.join(" ")).toContain("evidence_summary");});
 it("review approval does not promote and archive works", async()=>{const s=store(); const c=client(s); const p=await createOrRefreshShadowPackPreflight(c,{userId:USER,shadowPackId:"s1"}); const reviewed=await updateShadowPackPreflightReview(c,{userId:USER,preflightId:p.id,reviewerNotes:"ok",reviewerDecision:"approved_for_promotion"}); expect(reviewed.status).toBe("approved_for_promotion"); expect(s.memory_context_packs[0].status).toBe("active"); const archived=await archiveShadowPackPreflight(c,{userId:USER,preflightId:p.id}); expect(archived.status).toBe("archived");});
});
