/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { loadPandoraVerificationData } from "@/lib/services/pandora-verification-service";

type Row = Record<string, any>;
const USER = "user-1";
const OTHER = "other-user";
function makeClient(store: Record<string, Row[]>, failTables: string[] = [], ops: string[] = []) {
  return { from(table: string) { if (failTables.includes(table)) throw new Error("missing"); let selected = [...(store[table] ?? [])]; const builder: any = { select() { return builder; }, eq(k: string, v: any) { selected = selected.filter((r) => r[k] === v); return builder; }, order(k: string) { selected = selected.sort((a,b)=>String(b[k]??"").localeCompare(String(a[k]??""))); return builder; }, limit(n: number) { selected = selected.slice(0,n); return builder; }, insert() { ops.push("insert"); return builder; }, update() { ops.push("update"); return builder; }, delete() { ops.push("delete"); return builder; }, upsert() { ops.push("upsert"); return builder; }, then(resolve: any, reject: any) { return Promise.resolve({ data: selected, error: null }).then(resolve, reject); } }; return builder; } } as any;
}
function pack(id: string, namespace: "real_life"|"au", status="active", user_id=USER): Row { return { id, user_id, namespace, pack_type: "master", status, title: id, created_at: id }; }
function base() { return { memory_context_packs: [pack("rl-active", "real_life"), pack("rl-old", "real_life", "archived"), pack("au-active", "au"), pack("au-old", "au", "superseded"), pack("other", "real_life", "active", OTHER)], audit_logs: [{ id: "a1", user_id: USER, namespace: "real_life", action: "memory_context_pack_distilled", record_id: "rl-active", created_at: "2026-07-03T00:00:00Z" }, { id: "s1", user_id: USER, namespace: "real_life", action: "first_live_append_proof_executed", record_id: "m1", created_at: "2026-07-03T01:00:00Z" }, { id: "other-a", user_id: OTHER, namespace: "au", action: "memory_context_pack_distilled", record_id: "x", created_at: "x" }], retrieval_logs: [] }; }

describe("loadPandoraVerificationData", () => {
  it("passes exactly one active master per namespace and hides other users", async () => { const data = await loadPandoraVerificationData(makeClient(base()), { userId: USER }); expect(data.invariantStatus.exactlyOneActiveMasterPerNamespace).toBe("pass"); expect(JSON.stringify(data)).not.toContain(OTHER); });
  it("fails duplicate active master in real_life", async () => { const s = base(); s.memory_context_packs.push(pack("rl-dup", "real_life")); const data = await loadPandoraVerificationData(makeClient(s), { userId: USER }); expect(data.namespaces.find((n)=>n.namespace==="real_life")?.status).toBe("fail"); expect(data.invariantStatus.noDuplicateActiveMaster).toBe("fail"); });
  it("fails duplicate active master in au", async () => { const s = base(); s.memory_context_packs.push(pack("au-dup", "au")); const data = await loadPandoraVerificationData(makeClient(s), { userId: USER }); expect(data.namespaces.find((n)=>n.namespace==="au")?.status).toBe("fail"); expect(data.invariantStatus.noDuplicateActiveMaster).toBe("fail"); });
  it("shows archived previous master and warns when missing", async () => { const data = await loadPandoraVerificationData(makeClient(base()), { userId: USER }); expect(data.namespaces[0].previousArchivedMaster?.id).toBe("rl-old"); const s = base(); s.memory_context_packs = s.memory_context_packs.filter((p)=>!(p.namespace==="au" && p.status!=="active")); const missing = await loadPandoraVerificationData(makeClient(s), { userId: USER }); expect(missing.namespaces.find((n)=>n.namespace==="au")?.status).toBe("warning"); });
  it("marks retrieval eval missing as not_run and present as real", async () => { const missing = await loadPandoraVerificationData(makeClient(base()), { userId: USER }); expect(missing.retrievalEval.status).toBe("not_run"); const s = base(); s.retrieval_logs.push({ id: "r1", user_id: USER, namespace: "real_life", retrieval_service: "internal_eval", created_at: "2026-07-03" }); const present = await loadPandoraVerificationData(makeClient(s), { userId: USER }); expect(present.retrievalEval).toMatchObject({ status: "pass", latestRunId: "r1", realResultAvailable: true }); });
  it("warns when audit or table reads are missing and never mutates", async () => { const ops: string[] = []; const data = await loadPandoraVerificationData(makeClient({ memory_context_packs: [] }, ["audit_logs"], ops), { userId: USER }); expect(data.warnings.length).toBeGreaterThan(0); expect(data.smokeEvidence.status).toBe("not_run"); expect(ops).toEqual([]); });
  it("never mixes AU and real_life rows", async () => { const data = await loadPandoraVerificationData(makeClient(base()), { userId: USER }); expect(data.namespaces.find((n)=>n.namespace==="real_life")?.newestActiveMaster?.id).toBe("rl-active"); expect(data.namespaces.find((n)=>n.namespace==="au")?.newestActiveMaster?.id).toBe("au-active"); });
});
