/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { archivePromotionRequest, createOrRefreshPromotionRequest, submitPromotionRequest, updatePromotionRequestReview } from "@/lib/services/pandora-promotion-request-service";
const USER="11111111-1111-4111-8111-111111111111", OTHER="22222222-2222-4222-8222-222222222222";
type Store=Record<string, any[]>;
function client(store:Store){ return { from(table:string){ const eqs:Record<string,any>={}; let lim=Infinity; let patch:any; let inserted:any; const rows=()=> (store[table]??[]).filter(r=>Object.entries(eqs).every(([k,v])=>r[k]===v)).slice(0,lim); const b:any={ select(){return b}, eq(k:string,v:any){eqs[k]=v;return b}, order(){return b}, limit(n:number){lim=n;return b}, single(){return b}, insert(row:any){inserted=Array.isArray(row)?row[0]:row; store[table]=store[table]??[]; store[table].push(inserted); return b}, update(row:any){patch=row; return b}, then(res:any,rej:any){ if(patch){ const r=rows()[0]; if(r) Object.assign(r,patch); return Promise.resolve({data:r??null,error:r?null:{message:"missing"}}).then(res,rej)} return Promise.resolve({data:inserted??rows(),error:null}).then(res,rej)}}; return b; }} as any; }
function store(status="approved_for_promotion", risk="low"):Store{return { pandora_shadow_context_packs:[{id:"s1",user_id:USER,request_id:"req",namespace:"real_life",pack_type:"master_candidate",status:"reviewed",title:"S",summary:"shadow",source_window:{},candidate_payload:{},evidence:{},warnings:[],created_at:"2026-01-01",updated_at:"2026-01-01"}], pandora_shadow_pack_preflights:[{id:"p1",user_id:USER,shadow_pack_id:"s1",namespace:"real_life",active_master_pack_id:"m1",request_id:"pre",status,diff_summary:{active_master_pack_id:"m1",shadow_pack_id:"s1",namespace:"real_life",added_keys:[],removed_keys:[],changed_keys:[],unchanged_keys:[],source_event_count_delta:0,open_loop_count_delta:0,needs_review_count_delta:0,top_recent_summary_count:1,evidence_summary_changed:false,has_active_master:true,generated_at:"2026-01-01"},risk_summary:{status:risk,score:risk==="high"?80:risk==="blocked"?100:10,reasons:[],blockers:risk==="blocked"?["blocked risk"]:[],warnings:[]},reviewer_notes:"",reviewer_decision:"approved_for_promotion",warnings:[],created_at:"2026-01-01",updated_at:"2026-01-01"}], pandora_promotion_requests:[], pandora_promotion_request_events:[], memory_context_packs:[{id:"m1",user_id:USER,namespace:"real_life",pack_type:"master",status:"active"}], memory_events:[]};}
describe("promotion request service",()=>{
 it("creates, refreshes, submits, approves, and archives without core memory writes", async()=>{const s=store(); const c=client(s); const a=await createOrRefreshPromotionRequest(c,{userId:USER,preflightId:"p1"}); const b=await createOrRefreshPromotionRequest(c,{userId:USER,preflightId:"p1"}); expect(a.id).toBe(b.id); expect(s.pandora_promotion_requests).toHaveLength(1); expect(a.promotion_plan.execution_available).toBe(false); const submitted=await submitPromotionRequest(c,{userId:USER,promotionRequestId:a.id}); expect(submitted.status).toBe("submitted"); const approved=await updatePromotionRequestReview(c,{userId:USER,promotionRequestId:a.id,reviewerNotes:"ok",reviewerDecision:"approved"}); expect(approved.status).toBe("approved"); const archived=await archivePromotionRequest(c,{userId:USER,promotionRequestId:a.id}); expect(archived.status).toBe("archived"); expect(s.memory_context_packs).toHaveLength(1); expect(s.memory_context_packs[0].status).toBe("active"); expect(s.memory_events).toHaveLength(0);});
 it("blocks cross-user or unapproved preflights", async()=>{await expect(createOrRefreshPromotionRequest(client(store()),{userId:OTHER,preflightId:"p1"})).rejects.toThrow(/not found/); const s=store("reviewed"); const r=await createOrRefreshPromotionRequest(client(s),{userId:USER,preflightId:"p1"}); expect(r.status).toBe("blocked"); await expect(submitPromotionRequest(client(s),{userId:USER,promotionRequestId:r.id})).rejects.toThrow(/draft/);});
 it("risk blocked creates blocked request and high risk creates warning", async()=>{let r=await createOrRefreshPromotionRequest(client(store("approved_for_promotion","blocked")),{userId:USER,preflightId:"p1"}); expect(r.status).toBe("blocked"); r=await createOrRefreshPromotionRequest(client(store("approved_for_promotion","high")),{userId:USER,preflightId:"p1"}); expect(r.status).toBe("draft"); expect(r.warnings.join(" ")).toContain("high");});
});
