import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "fs";
import { join } from "path";
import Page from "@/app/admin/memory/safe-persistence-phase-close/page";
import { createSafePersistencePhaseCloseRouteHandler } from "@/lib/api/safe-persistence-phase-close-route-handler";
import { buildSafePersistencePhaseCloseReport } from "@/lib/services/safe-persistence-phase-close-report-builder";
import { validateSafePersistencePhaseClose } from "@/lib/services/safe-persistence-phase-close-validator";
import { exportSafePersistencePhaseCloseReport } from "@/lib/services/safe-persistence-phase-close-export";

const sessionResult = { ok: true, session: { userId: "raw-user", authenticated: true, allowedNamespaces: ["real_life"], adminCapabilities: ["memory:phase-close"], isInternalOperator: true, isPersistenceOperator: false, sessionSource: "test", serverDerivedOnly: true, clientUserIdAccepted: false, publicReadAllowed: false, publicPersistenceAllowed: false, serviceRoleUsed: false }, blockers: [] };
const artifactProofs = { reviewQueueProof: "review", approvedReviewAppendProof: "append", manualWorkflowProof: "manual", fixtureDryRunProof: "fixture", liveOneItemWorkflowProof: "live", proofPackProof: "proof", controlledRunbookProof: "runbook", readinessLockProof: "readiness", emergencyStopProof: "stop", executionPacketProof: "packet", proofCaptureProof: "capture", readbackVerifierProof: "readback", browserVerifierProof: "browser", auditVerifierProof: "audit", appendOnlyProof: "append-only", redactionProof: "redaction" };
const good = { sessionResult, namespace: "real_life", allowedNamespaces: ["real_life"], ...artifactProofs };
const codes = (x: object) => validateSafePersistencePhaseClose({ ...good, ...x }).blockers.map((b) => b.code);

describe("safe persistence phase close", () => {
  it("validator blocks missing safety artifacts and unsafe gates", () => { expect(codes({ sessionResult: undefined })).toContain("missing_session"); expect(codes({ sessionResult: { ...sessionResult, session: { ...sessionResult.session, isInternalOperator: false, isPersistenceOperator: false, adminCapabilities: [] } } })).toContain("missing_operator_capability"); expect(codes({ user_id: "evil" })).toContain("client_user_id_rejected"); expect(codes({ userId: "evil" })).toContain("client_user_id_rejected"); expect(codes({ namespace: undefined })).toContain("missing_namespace"); expect(codes({ namespace: "au", allowedNamespaces: ["real_life"] })).toContain("namespace_not_allowed"); for (const key of Object.keys(artifactProofs)) expect(codes({ [key]: undefined })).toContain(`missing_${key}`); expect(codes({ emergencyStopOn: true })).toContain("emergency_stop_on"); expect(codes({ publicPersistenceEnabled: true })).toContain("public_persistence_enabled"); expect(codes({ productionIngestEnabled: true })).toContain("production_ingest_enabled"); expect(codes({ publicReadEnabled: true })).toContain("public_read_enabled"); expect(codes({ modelCallsEnabled: true })).toContain("model_calls_enabled"); expect(codes({ embeddingsEnabled: true })).toContain("embeddings_enabled"); expect(codes({ semanticRetrievalEnabled: true })).toContain("semantic_retrieval_enabled"); expect(codes({ gptActionsEnabled: true })).toContain("gpt_actions_enabled"); expect(codes({ mcpEnabled: true })).toContain("mcp_enabled"); expect(codes({ privilegedKeyExposureDetected: true })).toContain("privileged_key_exposure_detected"); expect(codes({ rawReport: { memoryText: "x", evidenceText: "x", rawUserId: "u", idempotencyKey: "k", secret: "s", rawErrors: "stack" } })).toContain("unsafe_report_content_detected"); });
  it("builder and export are report-only, deterministic, and redacted", () => { const a = buildSafePersistencePhaseCloseReport(good); const b = buildSafePersistencePhaseCloseReport(good); expect(a.ok).toBe(true); expect(a.performsPersistence).toBe(false); expect(a.calledPublicRoute).toBe(false); expect(a.calledModel).toBe(false); expect(a.retrievalPhaseStarted).toBe(false); expect(a.contextAssemblyStarted).toBe(false); expect(a.report?.phaseCloseId).toBe(b.report?.phaseCloseId); expect(a.report?.finalNextStep).toContain("Manually perform one controlled internal append"); expect(a.report?.retrievalStatus).toBe("not_enabled"); expect(a.report?.contextAssemblyStatus).toBe("not_enabled"); const exported = exportSafePersistencePhaseCloseReport(a.report!); const text = JSON.stringify(exported); expect(text).not.toContain("raw-user"); expect(text).not.toContain("idempotencyKey"); expect(text).not.toContain("memory text"); expect(text).not.toContain("evidence text"); expect(text).not.toContain("raw error"); });
  it("route is safe and validation-only", async () => { const h = createSafePersistencePhaseCloseRouteHandler(); const get = await h.GET(); expect(get.status).toBe(200); const getText = JSON.stringify(await get.json()); expect(getText).toContain("Phase-close report only"); expect(getText).toContain("This page does not execute memory persistence"); const disabled = await h.POST(new Request("https://x", { method: "POST", headers: { "x-pandora-internal-phase-close-mode": "safe-persistence-foundation" }, body: JSON.stringify(good) }) as never); expect(disabled.status).toBe(501); const disabledJson = await disabled.json(); expect(disabledJson.performsPersistence).toBe(false); const badUser = await h.POST(new Request("https://x", { method: "POST", headers: { "x-pandora-internal-phase-close-mode": "safe-persistence-foundation" }, body: JSON.stringify({ user_id: "evil" }) }) as never); expect(badUser.status).toBe(400); const missingHeader = await h.POST(new Request("https://x", { method: "POST", body: JSON.stringify(good) }) as never); expect(missingHeader.status).toBe(403); });
  it("UI renders required safety copy", () => { const html = renderToStaticMarkup(<Page />); for (const t of ["Safe persistence/operator phase", "Phase-close report only", "This page does not execute memory persistence", "Ready for one controlled manual append only", "Stop after one memory append", "Do not batch", "Do not proceed to retrieval", "Emergency stop overrides readiness", "Public persistence is disabled", "Production ingest writes are disabled", "Public reads are disabled", "No model calls, embeddings, or semantic retrieval", "ChatGPT context assembly is not enabled", "All memory persistence remains append-only", "Proof capture is append-only", "Raw memory text and evidence are redacted", "AU/story memory cannot become real-life evidence", "Real-life memory cannot enter AU unless explicitly fictionalized and reviewed"]) expect(html).toContain(t); expect(html).toContain("disabled"); });
  it("new phase-close files avoid forbidden integrations and existing surfaces remain safe", () => { const root = process.cwd(); const files = ["lib/services/safe-persistence-phase-close-contract.ts","lib/services/safe-persistence-phase-close-validator.ts","lib/services/safe-persistence-phase-close-report-builder.ts","lib/services/safe-persistence-phase-close-export.ts","lib/api/safe-persistence-phase-close-route-handler.ts","app/api/admin/memory/safe-persistence-phase-close/route.ts"]; const text = files.map((f) => readFileSync(join(root, f), "utf8")).join("\n"); const imports = text.split("\n").filter((line) => line.startsWith("import ")).join("\n"); expect(imports).not.toMatch(/from [^;]*(openai|anthropic|embedding|vector|pgvector|semantic|gpt-actions|mcp)|SUPABASE_SERVICE_ROLE|createClient/i); expect(text).not.toContain(["service", "role"].join("-")); expect(readFileSync(join(root, "app/api/memory/ingest/route.ts"), "utf8")).toMatch(/disabled|createMemoryIngestRouteHandler/i); expect(readFileSync(join(root, "app/api/memory/review/[id]/persist/route.ts"), "utf8")).toMatch(/disabled/i); expect(readFileSync(join(root, "lib/services/persisted-memory-browser-loader.ts"), "utf8")).not.toMatch(/insert|update|delete|upsert/i); expect(readFileSync(join(root, "app/api/admin/memory/live-one-item/route.ts"), "utf8")).toMatch(/createLiveOneReviewedItemWorkflowRouteHandler\(\)/); expect(readFileSync(join(root, "lib/services/first-live-append-proof-capture-runner.ts"), "utf8")).toMatch(/proofCaptureOnly/); expect(readFileSync(join(root, "lib/services/first-controlled-live-append-packet-contract.ts"), "utf8")).toMatch(/packetOnly/); });
});
